[#935] Fix SIG-11 and/or incorrect ERR_UNKNOWN_TABLE error on an invalid SQL command
Background
----------
* Below is pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/935#description.

  I typed the command `h;` at the `OCTO>` prompt. And then pressed `Enter`. I got an `ERR_UNKNOWN_TABLE`
  error. The command `h` got treated as a table name by the parser. Not sure how. Postgres, on the
  other hand, issues a more accurate syntax error.

  **Octo output**
  ```sql
  OCTO> h;
  [ERROR]: ERR_UNKNOWN_TABLE: Unknown table: H
  LINE 1:1: h;
            ^
  ```

  **Postgres output**
  ```sql
  names=> h;
  ERROR:  syntax error at or near "h"
  LINE 1: h;
          ^
  ```

* Below is pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/935#note_1232011274.

  While analyzing the issue reported in the previous bullet, I noticed the following additional issues
  which I believe are related so noting them here even though the symptom here is different (a SIG-11).

  ```sql
  OCTO> IDENTIFIER_ALONE;
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 51866 has been killed by a signal 11 at address 0x000055CF87A10FC3 (vaddr 0x0000000000000004)
  %YDB-F-SIGMAPERR, Signal was caused by an address not mapped to an object

  OCTO> IDENTIFIER_BACK_TICK;
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 51881 has been killed by a signal 11 at address 0x0000558DDC694FC3 (vaddr 0x0000000000000004)
  %YDB-F-SIGMAPERR, Signal was caused by an address not mapped to an object

  OCTO> IDENTIFIER_PERIOD_IDENTIFIER;
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 51890 has been killed by a signal 11 at address 0x000055AC41C19FC3 (vaddr 0x0000000000000004)
  %YDB-F-SIGMAPERR, Signal was caused by an address not mapped to an object
  ```

Issue
-----
* When an invalid command is specified, it is getting treated as a table name by the Octo parser.
  To determine why this is the case, I ran the following.

  ```sh
  cd YDBOcto/build
  cd ../src
  bison --warnings=none -v -d -o ../build/parser.c ../build/parser.y
  cat ../build/parser.output
  ```

* I searched for `State 0` (which is the start of parsing a SQL query) in the
  `../build/parser.output` file and found the following.

  ```
   1516 State 0
   1517
   1518     0 $accept: . sql_statement $end
   1519
   1520     error                         shift, and go to state 1
   1521     BEG                           shift, and go to state 2
   1522     COMMIT                        shift, and go to state 3
   1523     CREATE                        shift, and go to state 4
   1524     DELETE                        shift, and go to state 5
   1525     DISCARD                       shift, and go to state 6
   1526     DROP                          shift, and go to state 7
   1527     EXTRINSIC_FUNCTION            shift, and go to state 8
   1528     INTRINSIC_FUNCTION            shift, and go to state 9
   1529     IDENTIFIER_ALONE              shift, and go to state 10
   1530     IDENTIFIER_BACK_TICK          shift, and go to state 11
   1531     IDENTIFIER_PERIOD_IDENTIFIER  shift, and go to state 12
   1532     INDEX                         shift, and go to state 13
   1533     INSERT                        shift, and go to state 14
   1534     SELECT                        shift, and go to state 15
   1535     SET                           shift, and go to state 16
   1536     SHOW                          shift, and go to state 17
   1537     TABLE                         shift, and go to state 18
   1538     TRUNCATE                      shift, and go to state 19
   1539     UPDATE                        shift, and go to state 20
   1540     VALUES                        shift, and go to state 21
   1541     LEFT_PAREN                    shift, and go to state 22
   1542     SEMICOLON                     shift, and go to state 23
   1543     ENDOFFILE                     shift, and go to state 24
   1544     EXIT                          shift, and go to state 25
   1545     QUIT                          shift, and go to state 26
   1546     HISTORY                       shift, and go to state 27
   1547     DISPLAY                       shift, and go to state 28
  ```

* Notice `SELECT` in line 1534 above. That is a valid keyword to start a SQL query.
  All other lines listed above are valid beginnings of a SQL command/query in a similar fashion
  with the exception of lines 1527-1531.

* Line 1529 mentions `IDENTIFIER_ALONE` which is related to the queries listed in the
  `Background` section.

* What this means is that an identifier can be a valid start of a SQL query in the grammar
  that Octo uses.

* This is incorrect and is the root cause of the issue.

* I traced the grammar rules from `sql_statement` (in `build/parser.y`) and removed the right hand
  side rules of it one at a time (finding where each right hand rule is defined and going to its
  right hand rule etc.). And reran the `bison` command listed above to see when the `IDENTIFIER_ALONE`
  token disappears from the `State 0` list.

* I found that the reason for this is the `joined_table` rule which is one of the right hand sides
  of the `query_expression` rule (line 1179 below).

  **src/parser.y**
  ```yacc
   1177 query_expression
   1178   : non_join_query_expression { $$ = $non_join_query_expression; }
   1179   | joined_table { $$ = $joined_table; }
   1180   ;
  ```

* And a `joined_table` rule matches a `cross_join` rule (line 361) which in turn matches a `table_reference`
  (line 367 below) for the start of the rule and that in turn can match any identifier which is why an
  identifier ends up being a valid start of a SQL query.

  **src/parser/select.y**
  ```yacc
    360 joined_table
    361   : cross_join { $$ = $cross_join; }
    362   | qualified_join { $$ = $qualified_join; }
    363   | LEFT_PAREN joined_table RIGHT_PAREN { $$ = $2; }
    364   ;
    365
    366 cross_join
    367   : table_reference CROSS JOIN table_reference {
    368       SqlJoin *left, *right;
  ```

Fix
---
* I cannot think of any reason why a `joined_table` is a valid `query_expression`. And so I decided
  that the right fix is to remove line 1179 in `src/parser.y` above. There were a couple more such
  occurrences in the same file and those are removed as well.

* With these changes, the following disappeared from the `State 0` list of valid tokens.
  - EXTRINSIC_FUNCTION
  - INTRINSIC_FUNCTION
  - IDENTIFIER_ALONE
  - IDENTIFIER_BACK_TICK
  - IDENTIFIER_PERIOD_IDENTIFIER

* And I get the following output for the queries mentioned in the `Background` section. Which in my
  opinion is a more user-friendly error message.

  ```sql
  OCTO> h;
  LINE 1:1: h;
            ^
  syntax error, unexpected IDENTIFIER_ALONE

  OCTO> IDENTIFIER_ALONE;
  LINE 1:1: IDENTIFIER_ALONE;
            ^^^^^^^^^^^^^^^^
  syntax error, unexpected IDENTIFIER_ALONE

  OCTO> IDENTIFIER_BACK_TICK;
  LINE 1:1: IDENTIFIER_BACK_TICK;
            ^^^^^^^^^^^^^^^^^^^^
  syntax error, unexpected IDENTIFIER_BACK_TICK

  OCTO> IDENTIFIER_PERIOD_IDENTIFIER;
  LINE 1:1: IDENTIFIER_PERIOD_IDENTIFIER;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  syntax error, unexpected IDENTIFIER_PERIOD_IDENTIFIER
  ```

Tests
-----
* A new `test_basic_parsing/TBP006` subtest verifies the fix.

* Additionally, the following existing test reference files needed fixing to reflect the
  revised error message due to the above code changes.
  - tests/outref/TAS01.ref
  - tests/outref/TGB21_errors.ref
  - tests/outref/TML004.ref
  - tests/outref/TML006.ref
  - tests/outref/TML007.ref

Misc
----
* Removing a few grammar rules in `src/parser.y` reduced the number of pre-existing `shift/reduce`
  conflicts by 1 (from 25 to 24) and so the following reference files were updated accordingly.
  - tools/ci/expected_warnings-release.ref
  - tools/ci/expected_warnings.ref