Fix asan-ubuntu job failure due to unknown -fno-var-tracking-assignments (regression in 6fb174c0)
Background
----------
* The `asan-ubuntu` pipeline job failed at https://gitlab.com/YottaDB/DBMS/YDBOcto/-/jobs/7779946857
  with the following error.

  ```
  error: unknown argument: '-fno-var-tracking-assignments' [clang-diagnostic-error]
  ```

Issue
-----
* The error happened at line 639 below.

  **tools/ci/build.sh**
  ```sh
    638         echo "# Check for unexpected warning(s) from clang-tidy ..."
    639         ../tools/ci/clang-tidy-all.sh > clang_tidy_warnings.txt 2>/dev/null
  ```

* The `-fno-var-tracking-assignments` flag was added in commit 6fb174c0 but it turns out to be
  a gcc-only option. clang or clang-tidy is not aware of it.

Fix
---
* The fix is to avoid using this flag/option in case the compiler is clang or clang-tidy. The
  former case is detectable using `CMAKE_COMPILER_IS_GNUCC`. But the latter is not easily
  detected. Therefore, we use the `CI_JOB_NAME` env var in this case and it would be set to
  `asan-ubuntu` or `asan-rocky` by the gitlab runner when the pipeline job is started.