[#727] Enhance tools/ci/build.sh to stop processing if ninja fails (due to build failure)
* This is an issue I noticed when running the pipeline with a compiler error in the code (in this
  case there was an error in `src/tmpl_invoke_deferred_plan.ctemplate.c` that has since been fixed).
  The below description assumes the error still exists so the issue and fix can be illustrated.

* The ninja build step in `tools/ci/build.sh` failed but the pipeline job proceeded further
  and failed at a much later point due to the lack of `octo` executable. On the other hand,
  I was expecting it to stop and exit right there. Below is the actual output of the pipeline job.

  https://gitlab.com/nars1/YDBOcto/-/jobs/1467230201

  ```
  + NINJA_STATUS='[ninja] [%f/%t] '
  + ninja
  /builds/nars1/YDBOcto/build/physical-lexer.c: In function "yylex":
  /builds/nars1/YDBOcto/build/physical-lexer.c:729:19: warning: variable "yylval" set but not used [-Wunused-but-set-variable]
    729 |         YYSTYPE * yylval;
        |                   ^~~~~~
  /builds/nars1/YDBOcto/build/parser.y: warning: 19 shift/reduce conflicts [-Wconflicts-sr]
  FAILED: src/CMakeFiles/libocto.dir/tmpl_invoke_deferred_plan.ctemplate.c.o
  /usr/bin/cc -DDISABLE_INSTALL=1 -I../src -I../src/optimization_transforms -I../src/physical -I../src/m_templates -I../src/helpers -I. -I/opt/yottadb/current -I/usr/include/readline -O2 -g -DNDEBUG   -Wall -Wextra -pedantic -Wmisleading-indentation -Wno-restrict -std=gnu11 -MD -MT src/CMakeFiles/libocto.dir/tmpl_invoke_deferred_plan.ctemplate.c.o -MF src/CMakeFiles/libocto.dir/tmpl_invoke_deferred_plan.ctemplate.c.o.d -o src/CMakeFiles/libocto.dir/tmpl_invoke_deferred_plan.ctemplate.c.o   -c src/tmpl_invoke_deferred_plan.ctemplate.c
  src/tmpl_invoke_deferred_plan.ctemplate.c: In function "tmpl_invoke_deferred_plan":
  src/tmpl_invoke_deferred_plan.ctemplate.c:32:41: error: expected ";" before ":" token
     32 |   assert(LP_SET_OPERATION == plan->type):
        |                                         ^
  ninja: build stopped: subcommand failed.
  + exit_status=0
  .
  .
  ```

* Notice the `exit_status=0` line above. The corresponding shell script line below is 52.

  ```sh
  tools/ci/build.sh
  -----------------
     47         else
     48                 # Only show warnings in the GitLab UI. Show the full output in `build_warnings.txt`.
     49                 # See https://ninja-build.org/manual.html#_environment_variables for the syntax of NINJA_STATUS.
     50                 NINJA_STATUS="[ninja] [%f/%t] " ninja | tee build_warnings.txt | grep -v '^\[ninja\] '
     51         fi
     52         exit_status=$?
     53         if [[ 0 != $exit_status ]]; then
     54                 echo "# $build_tool failed with exit status [$exit_status]. output follows below"
     55                 cat build_warnings.txt
     56                 exit $exit_status
     57         fi
  ```

* So `$?` ended up being `0` after the `ninja` command in line 50 above even though the `ninja` command
  failed. This is because it is part of a pipeline where the last command is a `grep` and that command
  succeeded.

* What we want is for `$?` to be non-zero if at least one of the commands in the pipeline fail. We can easily
  enable that using the `set -o pipeline` feature of bash. And that is exactly what is done in this commit.
  With that change `$?` correctly gets set to `1` in the above case when `ninja` fails even though `grep`
  succeeds in the same pipeline.