[#420] Implements random octo client selection
Randomized client selection is introduced in this commit
- List of clients under consideration are JDBC, PSQL and Octo
- All calls to the `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function will randomly select a client among the ones shown above with the exception of the following cases:
    1. When `usejdbc` argument is passed randomization is disabled and JDBC client is used for query execution
	2. Similarly `useocto` argument will disable randomization and Octo is used for query execution
    3. When Postgres version is less than 10, random selection of client happens excluding JDBC client from the list of clients

Previous to this commit:
- 2 cross check function interface (single query execution - `run_query_in_octo_and_postgres_and_crosscheck` and multiple query execution- `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries`) was present to perform Octo & Postgres cross check
- Both functions executed queries in Octo and Postgres without using any clients
- Single query interface `run_query_in_octo_and_postgres_and_crosscheck` can be passed `usejdbc` to perform cross check using JDBC driver

After this commit:
- Single cross check interface `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` (handles both single and multiple query execution). Reason behind having a single function is it helps to reduce code duplication with respect to randomization, enables single query execution to also go through randomized client selection, so the user doesn't have to remember 2 separate functions to achieve the same behavior and enables `usejdbc` usage for multiple query file execution as well.
- Cross check happens with client chosen at random
- The name of the cross check interface is the same as the previous multiple query function, i.e. `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries`
- All the arguments earlier given to `run_query_in_octo_and_postgres_and_crosscheck` function can be given to the new interface and can be expected to behave in same manner
- In addition to the earlier arguments, `useocto` is introduced with this interface. When this argument is passed the interface ensures cross check is performed between Octo and Postgres without JDBC or rocto usage.
- The implicit dependency on `test_port` variable which existed with single query `run_query_in_octo_and_postgres_and_crosscheck` function still exists
- Now, `run_query_in_octo_and_postgres_and_crosscheck` function is just a utility function used by the multiple query interface to execute the query and verify its output. Verification code which was present in `run_query_in_octo_and_postgres_and_crosscheck` has been moved to `run_query_verify`. This helps verification of results obtained from JDBC client. When JDBC client is selected, execution of all query files is carried out with a single database connection instead of establishing connection for each query.

Starting and stopping rocto by `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function:
1. If a subtest starts rocto either through setup or directly and sets `test_port` with rocto port value, then, `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function will not attempt to start rocto again. In this case stopping rocto is the responsibility of the test either through teardown or directly in a subtest. This allows tests to start rocto with different options like `start_rocto $test_port quiet --allowschemachanges`, `start_rocto $test_port --allowschemachanges`, `start_rocto 1337 verbose` etc
2. If a test doesn't start rocto then `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function when called starts and stops rocto as and when needed i.e. when JDBC client or PSQL client is being used to execute queries
3. In multiple `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function calls in the same subtest case:
    - If a subtest start's rocto then same port is used for invoking a randomly selected client. In this case when two or more `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function calls are present in a subtest, all the calls are using the same port but the client is being chosen at random.
	- If a subtest doesn't start rocto then each call of `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function (even in the same subtest) will start and stop rocto along with random client selection
4. `test_port` value is used to identify if rocto is started by a subtest. Internally `isnotexternal` variable is used to indicate if rocto is started by a subtest or `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function. If isnotexternal is set to 1, run_query_in_octo_and_postgres_and_crosscheck_multiple_queries has started rocto, otherwise a subtest has started rocto.
5. In case difference exists between psql.out and octo.out, before this commit, the execution of `run_query_in_octo_and_postgres_and_crosscheck` function stopped at the diff command and a test failure was issued by BATS. Now, execution of the function doesn't immediately stop. Instead, it runs `stop_rocto` and then issues `exit 1` which stops further execution and issues a test fail. In order to execute `stop_rocto`, the diff command was `||`'d with TRUE, so that the execution continued enough to call `stop_rocto`.

`start_rocto` itself calls `create_user` so it is not needed to be called from a subtest.

As comments are not yet handled by rocto in case of a JDBC client, we remove them before processing a query. Tracked by #541. When commented code is removed and nothing exists in a query file, the query execution is skipped for that file as it is empty.

`NULL` handling by Postgres fails for queries similar to one shown below. This happens only when Postgres is invoked through JDBC driver, due to the lack of support for `NULL` values in comparisons, e.g. in a WHERE clause. However, this isn't due to the right hand side, but rather to the left which for some reason cannot be implicitly converted to any particular type:
```
	SELECT * FROM (SELECT NULL AS col1, NULL AS col2) AS u1 WHERE u1.col1 = NULL;
	ERROR: failed to find conversion function from unknown to text
	SQL State: XX000
```
As this error was only noticed in Postgres versions less than 10 it was decided to exclude JDBC driver usage when performing a random client selection. Random selection of psql with rocto remains possible irrespective of the Postgres version. However, the JDBC driver is excluded from random client selection when the Postgres version is less than 10.

The `verify_output` function is updated to remove semicolons in `outref/$1.ref` and `clean_output.txt` when JDBC client is being used. This is because `test_where_in` `TWI12` fails when run using the JDBC client as its execution results in a physical plan having query information without a semicolon at the end of the query. Whereas when run using PSQL a semicolon is included.

`run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` function execution parameters, i.e. information about Postgres version, the client being used, and arguments given specific to JDBC driver usage, are captured in `env.out` file. This helps in identifying which parameters were used for test execution.

`test_random_octo_client` verifies if passing `usejdbc` and `useocto` as arguments to `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` exhibits the expected behavior, i.e. `usejdbc` utilizes the JDBC driver and rocto, while `useocto` performs the cross check between Octo and Postgres without using rocto or the JDBC client. In addition to this, the test also verifies `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` working in the presence of comments, blanks lines and commented queries.

JDBC client usage increased pipeline execution time drastically. Reducing number of queries generated by `test_sqllogic` and `test_query_generator` did not improve execution time. After some analysis it was found that JDBC client utilized `run_query.java` to execute queries and `run_query.java` attempts to establish connection with database for each query. This effort is quite redundant in case for `run_query_in_octo_and_postgres_and_crosscheck_multiple_queries` use cases. Additionally, having different query result files for different queries is unavoidable as cross check between Octo and Postgres requires sorting and row only count check in many cases. The approach of combining query results to a single file makes it hard to identify which query resulted in a failure as the output file in many cases gets sorted before cross check. Though the single result file approach gave the best pipeline execution time, it could not be used for the mentioned reason. So the code path was modified to accommodate multiple query execution under same database connection. This was achieved by a new helper program - `run_multiple_query_files.java`. It establishes connection once and iterates through all query files, executing them and storing results in separate files. Once the results are obtained `run_query_verify` is invoked to perform the cross check.

Other efforts to improve pipeline executions time:
-`test_sqllogic` and tests which call `run_querygenerator` (i.e.`test_query_generator` and `test_jdbc_connection`) now generate a single file with multiple queries instead of multiple single-query files. `split_query.py` in `test_helpers` takes care of splitting queries into separate files, so, by reducing the frequency of file access, pipeline execution time for the two tests improved.

Misc changes:
- This commit also corrects some usages of `$queryfile.sql` to `$queryfile.sql.inp`
- Included bug fix: tests/fixtures/gensetqueries.m used to generate queries without a semicolon ending the query. Now, a semicolon is appended at the end of the M program. This bug was noticed when `test_set_operations` failed when executed with this commit. Although the test failure was caused by `splitquery` python script (reason being queries not ending with semicolons), the original issue was that such a query when executed in Octo or Postgres, the execution would not have been completed till a semicolon is entered. Thus, incorrect results of Octo and Postgres (Although both being empty) were being compared.
- Included bug fix: when `grep` on `ORDER BY` was being executed in `run_query_in_octo_and_postgres_and_crosscheck` function to determine if sorting was required, if the queryfile had `#` commented lines and was passed to `removeInnerQuery` M program, the program would return the first line of copyright having all `#`'s and this would result in `ORDER BY` not being found in the file. As a result, the output was being sorted even when `ORDER BY` was present in query. This was not expected. Now, since all query files go through `splitquery` program, `#` commented lines and `--` commented lines are all removed and only a query is used when searching for `ORDER BY` as expected. This resulted in `test_inner_join_order_by` failure as `--sort-needed-check` was not part of the query and previous to the this commit it would pass because of the bug mentioned earlier. Now, `--sort-needed-check` has been added to queries in TIJOB01.sql-TIJOB12.sql, all tests pass (Why `--sort-needed-check` is required: After order by has completed ordering the results based on given columns, the resulting ordering of same valued cases are implementation dependent and at present, Octo results differ from Postgres in this scenario. Because of this reason `--sort-needed-check` is added to queries which belong to this category so that additional sorting is done to match Postgres output)
- Included bug fix: Previous to this commit tests/fixtures/TOJ03.m placed commented instructions like `--sort-needed-check` before the query in a separate line. But, now as the query goes through python script `splitquery` the lines are split into separate files and the commented instructions are lost. This resulted `test_outer_join` and `test_jdbc_connection` to fail. Now, to avoid losing the commented instruction, it is appended to the end of a query and the aforementioned tests pass.
- `tests/test_coerce_type.bats.in` when executed with JDBC client tends to not have a result set returned in `run_multiple_query_files.java` as a result the test fails. On manual verification even on Octo there is no row returned. So thought it would be best for now to `useocto` and have it execute as before.