[#579] Fix incorrect results from SELECT/UPDATE/DELETE if prior queries with OR conditions in WHERE clause errored out
Background
----------
* This started out as a specific issue in UPDATE then was observed in DELETE and was finally observed in SELECT.
  The details of each are provided below.

* Below is pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/579#note_1100898908

  This is yet another pre-existing issue in the UPDATE (#579) and/or DELETE command (#54) that I noticed
  while writing some #770 tests.

  Below is the test case. I create a table, insert 2 rows into it and then run a `delete from` command
  that removes both rows (see `DELETE 2` in line 10 below). I then verify that the table is empty and
  then rerun the same set of commands again except that this time I run a `update` command (line 18 below)
  which encounters a `ERR_DUPLICATE_KEY_VALUE` constraint violation error. This means the table should be
  in the exact same state as it was before line 9 below. But if I then run the same `delete from` command
  (line 25 below), it deletes only 1 row see `DELETE 1` in line 26 below). And a later select does confirm
  only 1 row got deleted. This is incorrect.

  It is not yet sure if the issue is with UPDATE or DELETE. But one thing that I noticed is that this failure
  requires one to use the OR operator in the WHERE clause of both the UPDATE and DELETE.

  ```sql
      1 OCTO> drop table if exists tmp;
      2 DROP TABLE
      3 OCTO> create table tmp (id1 integer primary key);
      4 CREATE TABLE
      5 OCTO> insert into tmp values (6);
      6 INSERT 0 1
      7 OCTO> insert into tmp values (0);
      8 INSERT 0 1
      9 OCTO> delete from tmp where (id1 != 3) or (id1 > 0);
     10 DELETE 2
     11 OCTO> select * from tmp;
     12 ID1
     13 (0 rows)
     14 OCTO> insert into tmp values (6);
     15 INSERT 0 1
     16 OCTO> insert into tmp values (0);
     17 INSERT 0 1
     18 OCTO> update tmp set id1 = 2 where (id1 = 4) or (id1 != 5);
     19 [ERROR]: ERR_DUPLICATE_KEY_VALUE: Duplicate Key Value violates UNIQUE constraint TMP_pkey : Node ^%ydboctoDK8x9V2YiyPMRxcDYOMpB0K(2) already exists
     20 OCTO> select * from tmp;
     21 ID1
     22 0
     23 6
     24 (2 rows)
     25 OCTO> delete from tmp where (id1 != 3) or (id1 > 0);
     26 DELETE 1
     27 OCTO> select * from tmp;
     28 ID1
     29 0
     30 (1 row)
  ```

* Below is pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/579#note_1102236999

  This is yet another #579 issue that I noticed while testing #770. Below is a simple test case.

  ```sql
  drop table if exists tmp;
  create table tmp (id1 integer, id2 integer, id3 integer, id4 integer primary key);
  insert into tmp values (5, 6, 0, 3);
  insert into tmp values (1, 7, 5, 5);
  update tmp set id2 = 4, id3 = 2, id4 = 1 where (id3 != 0) and (id1 in (1)) or (id1 != 7);
  update tmp set id1 = 6, id2 = 1, id4 = 0 where (id4 < 7) or (id4 in (1, 2, 3)) and (id3 in (1, 2));
  ```

  As can be seen from the below outputs, Octo accepts the second `update` command without errors but Postgres
  issues a duplicate key value constraint violation error. This does look like an issue. Maybe related to
  other issues already reported above. But not sure so recording this separately.

  **Octo output**
  ```sql
  OCTO> drop table if exists tmp;
  DROP TABLE
  OCTO> create table tmp (id1 integer, id2 integer, id3 integer, id4 integer primary key);
  CREATE TABLE
  OCTO> insert into tmp values (5, 6, 0, 3);
  INSERT 0 1
  OCTO> insert into tmp values (1, 7, 5, 5);
  INSERT 0 1
  OCTO> update tmp set id2 = 4, id3 = 2, id4 = 1 where (id3 != 0) and (id1 in (1)) or (id1 != 7);
  [ERROR]: ERR_DUPLICATE_KEY_VALUE: Duplicate Key Value violates UNIQUE constraint TMP_pkey : Node ^%ydboctoDK8x9V2YiyPMRxcDYOMpB0K(1) already exists
  OCTO> update tmp set id1 = 6, id2 = 1, id4 = 0 where (id4 < 7) or (id4 in (1, 2, 3)) and (id3 in (1, 2));
  UPDATE 1
  ```

  **Postgres output**
  ```sql
  names=> drop table if exists tmp;
  NOTICE:  table "tmp" does not exist, skipping
  DROP TABLE
  names=> create table tmp (id1 integer, id2 integer, id3 integer, id4 integer primary key);
  CREATE TABLE
  names=> insert into tmp values (5, 6, 0, 3);
  INSERT 0 1
  names=> insert into tmp values (1, 7, 5, 5);
  INSERT 0 1
  names=> update tmp set id2 = 4, id3 = 2, id4 = 1 where (id3 != 0) and (id1 in (1)) or (id1 != 7);
  ERROR:  duplicate key value violates unique constraint "tmp_pkey"
  DETAIL:  Key (id4)=(1) already exists.
  names=> update tmp set id1 = 6, id2 = 1, id4 = 0 where (id4 < 7) or (id4 in (1, 2, 3)) and (id3 in (1, 2));
  ERROR:  duplicate key value violates unique constraint "tmp_pkey"
  DETAIL:  Key (id4)=(0) already exists.
  ```

* Below is pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/579#note_1105838798

  After analyzing https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/579#note_1100898908 and
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1219#note_1103987297, I have come to the conclusion
  that they are related as originally suspected. Not just that, I also found a test case involving `SELECT`
  (not `UPDATE` or `DELETE`) that has similar issues.

  Below is a simple example. The first query correctly reports 2 rows. Then I run a query that encounters
  an error. I then rerun the first query. And this time it reports only 1 row. Not the expected 2 rows.

  ```sql
  OCTO> select * from names where firstname = 'Joey' or firstname = (select firstname from names where firstname = 'Acid');
  ID|FIRSTNAME|LASTNAME
  4|Joey|
  1|Acid|Burn
  (2 rows)
  OCTO> select * from names where firstname = 'Joey' or firstname = (select firstname from names where firstname = 'Zero');
  [ERROR]: ERR_SUBQUERY_MULTIPLE_ROWS: More than one row returned by a subquery used as an expression
  OCTO> select * from names where firstname = 'Joey' or firstname = (select firstname from names where firstname = 'Acid');
  ID|FIRSTNAME|LASTNAME
  1|Acid|Burn
  (1 row)
  ```

Issue
-----
* Whenever an OR operator is involved in the WHERE clause, it is possible for multiple physical plans to be
  emitted. In that case, we avoid duplicate processing of the same row of the table across the multiple
  physical plans using the lvn `%ydboctozduplicate` (i.e. `PP_YDB_OCTO_ZDUPLICATE` macro).

* In the emitted M code, a `KILL` of this lvn was done `after` processing all the physical plans. This was
  the case for SELECT, UPDATE and DELETE.

* But this means that if ever there is a runtime error in the middle of executing the multiple physical plans,
  we could potentially issue an error in the M code and transfer control out of M into C in Octo and move on
  to executing the next SQL query/command.

* This would mean that the `%ydboctozduplicate` variable from the query/command that errored out will be left
  over in an incomplete state and affect the following query/command.

Fix
---
* The fix is to do the `KILL` of the lvn `before` processing all the physical plans.

* The changes involved the following files.
  - src/m_templates/tmpl_delete_from.ctemplate : DELETE command
  - src/m_templates/tmpl_physical_plan.ctemplate : SELECT command
  - src/m_templates/tmpl_update_table.ctemplate : UPDATE command

* This involved changing various pre-existing reference files due to the difference in the `KILL` placement.

Test
----
* A new `test_boolean_expression_expansion/TBEE05` bats subtest verifies this fix.