[pipeline] Avoid update query result validation when JDBC driver is used during test-auto-upgrade execution
Issue
--------
* When the older commit executes test using JDBC driver the result for INSERT/UPDATE/DELETE will be of the form
  `Number of rows updated = ##`. The latest commit then executes with Octo. Comparison between the two is difficult.
  ```
  --JDBC driver output
  # It would be non-zero only for INSERT INTO, DELETE FROM etc.
  # Note that the below would be 0 for CREATE/DROP commands
  Number of rows updated = 0

  --Octo output
  UPDATE 0
  ```

Solution
-----
* Avoid auto-upgrade test on subtests which use JDBC driver to execute `QueryGenerator.m` generated queries, when
  the INSERT/UPDATE/DELETE are among the generated queries. The result comparison in these cases are not easy
  for the following reasons
  * The results for a non-error case of insert/update/delete query needs to be formatted to the following based on the
    query type
    ```
    INSERT [0-9]* [0-9]*
    UPDATE [0-9]*
    DELETE [0-9]*
    ```
    from
    ```
    # It would be non-zero only for INSERT INTO, DELETE FROM etc.
    # Note that the below would be 0 for CREATE/DROP commands
    Number of rows updated = 0
    ```
    This is not simple. Then there is also the ERROR case scenario explained below.
  * For an error case of insert/update/delete query, formatting is required from the first part to the second shown below
    ```diff
    ERROR: NULL value in column ID violates NOT NULL constraint
    SQL State: 23502
    ---
    [ERROR]: ERR_NULL_COL_VALUE: NULL value in column ID violates NOT NULL constraint
    ```
* Since, both these types of queries are tested by PSQL client and Octo, more time is not invested to fix the above
   cases.
* This is one of several commits (70cf892e, 87525d6c, 0beb5bb1, 0893983f) that were added to stabilize the test-auto-upgrade job
  after the changes to QueryGenerator.m introduced by c581a95e commit.
* Note
  * That this change removes few code blocks which were introduced by previous commits (mentioned above) to handle the type of
  tests avoided by this commit as they are no longer used after this change.
  * Also, just allowing auto-upgrade test on SELECT queries from JDBC driver based test execution (which had INSERT/DELETE/UPDATE
    also) isn't possible as the older commit results (when running the auto-upgrade test) of SELECT queries
    would have been effected by the INSERT/DELETE/UPDATE queries that came before it. Skipping the INSERT/DELETE/UPDATE queries
    when using the latest commit in the test-auto-upgade test will effect the SELECT query results making it not comparable with
    the older commit results. Hence even this is avoided.