[#759] Fix TABLENAME.ASTERISK issues with GROUP BY, aggregate functions and type cast operator
Issue 1 : Incorrect results when TABLENAME.ASTERISK is used with GROUP BY and LEFT JOIN
=======================================================================================

Background
----------
* This is an issue that showed up as a pipeline failure (https://gitlab.com/YottaDB/DBMS/YDBOcto/-/jobs/1660946374).

* The actual query that failed in the pipeline is complex. But the bottomline is that Postgres had 1 more row of
  output than Octo.

* I was able to simplify the query further and come up with a test case that seemed to me like it is a
  Postgres issue with TABLENAME.ASTERISK syntax and that Octo is working right (this feature was implemented
  in #386). The Postgres developers clarified that it is a feature (for the full discussion, see
  https://www.postgresql.org/message-id/flat/0e0301d7bc59%24a1e416b0%24e5ac4410%24%40yottadb.com).

* Below is a simple example that shows the difference in behavior.

  ```sql
  $ cat tablenamestar.sql
  DROP TABLE IF EXISTS tmp;
  CREATE TABLE tmp (id INTEGER PRIMARY KEY, firstName VARCHAR(30), lastName VARCHAR(30));
  INSERT INTO tmp VALUES (1,'Acid','Burn');
  INSERT INTO tmp VALUES (2,'Joey',NULL);
  SELECT COUNT(t1.lastName) FROM tmp t2 LEFT JOIN (SELECT lastName FROM tmp) AS t1 ON (t2.firstName <= 'Acid') GROUP BY t1.lastName;
  SELECT COUNT(t1.*) FROM tmp t2 LEFT JOIN (SELECT lastName FROM tmp) AS t1 ON (t2.firstName <= 'Acid') GROUP BY t1.*;

  $ octo -f tablenamestar.sql
  COUNT
  0
  1
  (2 rows)
  COUNT
  1
  1
  (2 rows)

  $ psql name -f tablenamestar.sql
  count
  0
  1
  (2 rows)
  count
  1
  1
  0
  (3 rows)
  ```

* The same query using `t1.*` behaves differently when `t1.lastName` is instead used even though `t1` has
  only 1 column (`lastName`). This is because in the `GROUP BY t1.*`, the `t1.*` is considered as a record
  consisting of the individual values comprising the `t1` table.

  In one row, `t1.*` contains a `lastName` value of `NULL` (i.e. `ROW(NULL)`). In another row, due to the
  OUTER JOIN, the entire row of `t1` is treated as a `NULL` value (`composite NULL`).

* Postgres treats a `composite NULL` and a `ROW(NULL)` as different when it comes to `GROUP BY`.
  See below example for more details.

  Notice the `t2` column output in the first query shows up as `''` and `'()'`. While both of them are `NULL`
  they are different `NULL`s as indicated by the second query where the `GROUP BY t2.*` showing 2 rows instead of
  showing just 1 row of output (which it would have if the two `t2.*` NULL values were considered identical).

  ```sql
  names=> SELECT t1.id, t1.lastName, t2.*::record FROM names t1 LEFT JOIN (SELECT lastName FROM names) AS t2 ON (t1.firstName <= 'Acid') WHERE t1.id <= 1 and t2.lastName IS NULL;
  id|lastname|t2
  0|Cool|
  1|Burn|()
  (2 rows)
  names=> SELECT count(t2.*) FROM names t1 LEFT JOIN (SELECT lastName FROM names) AS t2 ON (t1.firstName <= 'Acid') WHERE t1.id <= 1 and t2.lastName IS NULL GROUP BY t2.*;
  count
  1
  0
  (2 rows)
  ```

* And with `t1.*` and OUTER JOINs, it is possible to see `composite NULL` values.

  Whereas with `t1.column` usage, it is only possible to see a scalar `NULL` value for that column.

  That is the reason why `GROUP BY` behaves differently with `t1.*` and `t1.lastName` even though `t1`
  contains only 1 column.

* Octo currently treats a `composite NULL` and a `ROW(NULL)` as identical when it comes to `GROUP BY`
  and is the cause of this issue.

Fix
---
The goal at a high level is for `GROUP BY t1.*` to distinguish an OUTER JOIN related NULL value for
the entire `t1` table from a `NULL` value in the only column of the `t1` table.

* The first step to getting there is for a `t1.*` specification if done inside a `GROUP BY` to NOT be
  expanded to a list of columns (as otherwise at M code generation time, we won't know whether it is a
  `GROUP BY t1.*` or `GROUP BY t1.lastName` specification since expanding the former would be identical
  to the latter). Only then can we handle `GROUP BY t1.*` differently from `GROUP BY t1.lastName` at
  M code generation time.

  Towards that, `src/qualify_statement.c` was changed to not invoke `process_table_asterisk_cla()` in
  case we find a `table.*` column alias while processing a `GROUP BY` clause.

  Because of this, `GROUP BY` related code inside `src/copy_column_list_alias_list.c` was removed as it is
  no longer possible. This code removal also meant the `table_alias` parameter that was passed into
  `copy_column_list_alias_list()` function was no longer used and so was removed resulting in
  changes to related/caller functions/files. One of those caller functions was `process_table_asterisk_cla()`
  which also no longer needed the `table_alias` parameter and so was removed resulting in an interface change
  that affected related/caller functions/files.

  And removing `GROUP BY` related code inside `src/copy_column_list_alias_list.c` also meant that logic
  in `src/qualify_statement.c` related to `group_by_column_number` maintenance could be simplified. It
  was previously done in 2 different places in the same file. One usage has now been removed and another
  usage now does it all the time (meaning `if` conditions were removed) making it simpler.

* Because a `GROUP BY t1.*` is not expanded, it is possible for `src/optimization_transforms/lp_emit_plan.c`
  to see a `TABLE_ASTERISK` type so that is now handled.

  Below is an example logical plan output where `type:` can now be `TABLE_ASTERISK`.

  ```yaml
  LP_GROUP_BY:
    LP_COLUMN_LIST:
      LP_WHERE:
        LP_COLUMN_ALIAS: NAMES(1).NAMES.*
        LP_COLUMN_LIST_ALIAS:
        - type: TABLE_ASTERISK
  ```

* The next step is to use the unexpanded `t1.*` (in the `GROUP BY t1.*`) at M code generation time.

  The main changes in this area are in `src/m_templates/tmpl_column_reference_common.ctemplate`. It now
  checks if the column alias is a `t1.*` type (i.e. `TABLENAME.ASTERISK`). If so, it returns `$ZYSQLNULL`
  in case of a `composite NULL` due to an `OUTER JOIN` and returns a value that is guaranteed to be not
  `$ZYSQLNULL` in case of a `ROW(NULL)`.  It does this by doing a `str2mval()` function invocation on each
  of the individual column values (note that this involves a recursive call to `tmpl_column_reference()`)
  so even if they are `$ZYSQLNULL`, the output of the function will not be `$ZYSQLNULL`. And concatenates
  all the non-$ZYSQLNULL column values (in mval transformed form) before returning.

  This also involved adding 4 new parameters to the `tmpl_column_reference_common()` function as these are
  needed to generate appropriate M code.
  - is_trigger : To pass to the recursive `tmpl_column_reference()` call.
  - dot_count : To pass to the recursive `tmpl_column_reference()` call as well as to generate additional
    surrounding M code.
  - depth : To ensure we use a lvn of the form `%ydboctoexpr(depth)` (to store intermediate results of the
    concatenation operation) that is guaranteed to be different from a similar lvn that could be potentially
    used by the caller function `tmpl_print_expression`.
  - sql_key : Used in case the `t1.*` usage is on a table `t1` that is a derived table (e.g. a result of a
    sub query evaluation).

  The following 2 callers of `tmpl_column_reference_common()` were changed to account for the new interface.
  - src/m_templates/tmpl_column_reference.ctemplate
  - src/m_templates/tmpl_print_expression.ctemplate

  Because `tmpl_column_reference_common()` needed the `depth` parameter and this was only available in a
  caller function `tmpl_print_expression()`, the `tmpl_column_reference()` function also needed an interface
  change to pass in the `depth` parameter to `tmpl_column_reference_common()`.  This parameter is incremented
  before passing it to avoid lvn (that stores temporary evaluations) collisions between caller and called function.
  And this resulted in changes in callers of `tmpl_column_reference()` to pass in the new `depth` parameter.

* Bumped the `FMT_PLAN_DEFINITION` macro in `src/octo.h` since generated M code as well as the M file name
  changed for `GROUP BY .*` queries.

Test
----
* New `test_tablename_asterisk/TTA004` and `test_tablename_asterisk/TTA005` subtests verify the fix works
  by exercising various queries. It runs them using the crosscheck utility thereby automatically verifying
  that Octo output matches that of Postgres.

* New `test_tablename_asterisk/TTA003` subtest verifies the `ERR_GROUP_BY_OR_AGGREGATE_FUNCTION` error is
  correctly issued by testing various queries.

  Various queries from the `TSCP14` and `TSCP15` subtests were moved to `tests/fixtures/TTA003.sql` as they
  now issue an error (they previously worked fine). This also resulted in the `TSCP15` subtest being removed
  as all queries in it had to be moved to the `TTA003` subtest.

* The `TTA005` subtest runs `CREATE TABLE` commands and therefore, it needed to be defined using the
  `ADD_BATS_TEST_DML` macro (not the `ADD_BATS_TEST` macro) in `cmake/bats-tests.cmake`.

* A new helper function `postgres_database_exists()` in `tests/test_helpers.bash.in` helps determine if a
  Postgres database with a name (`$1` parameter) exists. This function is now used in the following
  multiple places thereby avoiding code duplication.
  - `load_postgres_fixture()` function in `tests/test_helpers.bash.in`
  - `HP01` subtest in `tests/hello_psql.bats.in`

* Enhanced the `HP01` subtest in `tests/hello_psql.bats.in` to `DROP TABLE` all tables that are known to
  be created by other bats tests from Postgres. This way, in case any of those tests failed in a prior
  test run (in an in-house environment), they would be deleted before the `HP01` subtest starts as
  such leftover tables can otherwise cause this subtest to fail.

Misc
----
* Renamed `key->skip_column_reference_optimization` to `key->use_tmpl_emit_source_for_xref_key` since
  the previous name was incorrect on 2 fronts.
  - First, using `tmpl_key` vs `tmpl_emit_source` is not an optimization. We decide which one to use
    based on some conditions and it is needed for correctness, not performance.
  - Given this is no longer an optimization, the word `skip` does not make sense anymore as there is no
    optimization that is being skipped.

  This involved changes to various files that used this field including adding/revising comments.

Issue 2 : Issue error for SUM(t1.*) even if it has only one column
==================================================================

Background
----------
* Postgres disallows all aggregate functions except `COUNT` on `table.*`. That is, `SUM/MIN/MAX/AVG` generate
  an error if used with `table.*`. See below example.

  ```sql
  names=> select sum(n1.*) from (select id from names) n1;
  ERROR:  function sum(record) does not exist
  LINE 1: select sum(n1.*) from (select id from names) n1;
                 ^
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
  ```

* Octo currently allows such function usages but I think it would be better if Octo follows the same model
  as Postgres.

Fix
---
* The main fix is in `src/process_aggregate_function_table_asterisk.c` to not expand the `.*` syntax even
  in the case the table has only one column. This way we let `populate_data_type()` issue a
  `ERR_MISTYPED_FUNCTION_TABLE_ASTERISK` error (like it always did) in all cases where an aggregate function
  is used with the `.*` sytnax. This makes Octo behave consistently with Postgres.

* While at this, I noticed that a `ERR_MISTYPED_FUNCTION_TABLE_ASTERISK` error was previously being issued
  in `src/populate_data_type.c` for the `AVG` and `SUM` aggregate functions. But it was issuing a generic
  `ERR_MISTYPED_FUNCTION` error for the `MIN` and `MAX` aggregate functions. This seemed inconsistent so
  fixed `MIN` and `MAX` to also issue a `ERR_MISTYPED_FUNCTION_TABLE_ASTERISK` error if used with a `.*` syntax.

* The error message text for `ERR_MISTYPED_FUNCTION_TABLE_ASTERISK` in `src/errors.hd` was slightly modified
  now that the error is thrown even when the table has just one column.

* This meant some changes to `doc/errors.rst` too to keep it in sync with `src/errors.hd`.

* The following existing reference files needed an update because of the above code changes.
  - tests/outref/TSCP11_errors.ref
  - tests/outref/TSCP13_errors.ref

* The `test_select_columns_psql/TSCP14` subtest was reworked to test for `ERR_MISTYPED_FUNCTION_TABLE_ASTERISK`
  error (whereas previously it was testing that the queries worked fine in Octo).

  Queries that previously existed in this test that now work the same in both Octo and Postgres were moved
  to one of the below files so we can run them using the crosscheck test framework function and avoid having
  to maintain a reference file.
  - tests/fixtures/TSCP14_names.sql
  - tests/fixtures/TSCP14_names1col.sql

  Queries that previously existed in this test that error out in Octo were moved to the following file
  - tests/fixtures/TSCP14_errors.sql

  We maintain a new reference file `tests/outref/TSCP14.ref` for Octo's error output.

Issue 3 : Issue error for type cast operator on t1.*
====================================================

Background
----------
* I noticed a `SIG-11` when a `type cast` is attempted on a `table.*` column reference. Note how `sum(n1.*)`
  works fine below but `sum(n1.*::integer)` gets a `SIG-11`.

  ```sql
  OCTO> select sum(n1.*) from (select id from names) n1;
  SUM
  15
  (1 row)

  OCTO> select sum(n1.*::integer) from (select id from names) n1;
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 37335 has been killed by a signal 11 at address 0x000055D35700D766 (vaddr 0x00000000
  00000000)
  %YDB-F-SIGMAPERR, Signal was caused by an address not mapped to an object
  ```

* Postgres disallows the type cast operator on `table.*` as can be seen below.

  ```sql
  names=> select sum(n1.*::integer) from (select id from names) n1;
  ERROR:  cannot cast type record to integer
  LINE 1: select sum(n1.*::integer) from (select id from names) n1;
                         ^
  ```

* It would be best if Octo does the same. That would automatically fix the `SIG-11`.

Fix
---
* `src/populate_data_type.c` now issues a `ERR_TYPE_CAST_TABLE_ASTERISK` error if it notices a type cast
  operator being attempted on a `TABLENAME.ASTERISK` syntax (e.g. `t1.*::integer`).

* This involved changes to the following additional files.
  - doc/errors.rst : Document new `ERR_TYPE_CAST_TABLE_ASTERISK` error.
  - src/error_codes.hd : Add new `PSQL_Code_Cannot_Coerce` error code type.
  - src/errors.hd : Add new `ERR_TYPE_CAST_TABLE_ASTERISK` error with a type `PSQL_Code_Cannot_Coerce`.

Test
----
* The `test_tablename_asterisk/TTA003` subtest has been enhanced to test various queries that now issue the
  `ERR_TYPE_CAST_TABLE_ASTERISK` error.