[#874] Issue ERR_GROUP_BY_OR_AGGREGATE_FUNCTION error when outer query un-grouped column is used in inner query GROUP BY
**Issue**

Refer to https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1062#note_1034387577 for detail description of the issue.

Fundamentally:
* Inner query is having an un-grouped outer query column in the GROUP BY clause. This is invalid.
* To be explicit, above point is only true if outer query has some form of grouping element i.e. either usage of GROUP BY/HAVING clause or aggregate function. Only then, if the outer query column reference (which is not in the outer query GROUP BY clause) gets used in the inner query GROUP BY clause an error needs to be issued saying un-grouped column reference from outer query is being used.
* Example:
  ```sql
  names=> select 1 from names n1 having exists(select 1 from names n2 group by n1.firstname);
  ERROR:  subquery uses ungrouped column "n1.firstname" from outer query
  LINE 1: ... n1 having exists(select 1 from names n2 group by n1.firstna...
                                                               ^
  ```
  Octo currently considers such queries valid and outputs the following result:
  ```sql
  OCTO>  select 1 from names n1 having exists(select 1 from names n2 group by n1.firstname);
  ???
  1
  (1 row)
  ```
* Octo's GROUP BY processing needs to be updated to issue error in such cases.

**Analysis**

1st step:
  * The code currently doesn't consider the fact that GROUP BY clause also needs to go through GROUP BY related validations and since outer query columns are mostly constants to the inner query's GROUP BY, outer query column references are removed from the inner query GROUP BY clause in qualify_query()
  * So the first thing to be done is avoiding removal of outer query column references from inner query GROUP BY clause untill all validations are complete.

2nd step:
  * GROUP BY validations in general are performed in the second iteration of qualify_query() FOR loop. In a query where only one query level is present, qualify_query() FOR loop didn't call qualify_statement() on GROUP BY clause as it was not expected to undergo GROUP BY validations.
  * `table_alias->do_group_by_checks` and `table_alias->aggregate_function_or_group_by_or_having_specified` are used to prevent second iteration on GROUP BY clause.
  * Why `table_alias->aggregate_function_or_group_by_or_having_specified` is required is lets say we have 2 levels in the query and outer query is having a subquery in having clause and the subquery (inner query) is having an outer query column in its GROUP BY clause. Following represents how the code execution takes place.
  * Consider the query in issue section above
  * Consider outer query's qualify_query() FOR loop, 1st iteration
    * It calls qualify_statement() on the HAVING clause which has a subquery
    * qualify_statement() invokes qualify_query() on the subquery
    * We reach inner query's qualify_query() FOR loop, 1st iteration
      * It is checked whether `table_alias->do_group_by_checks` is set or not. At this time it won't be so execution proceeds and checks whether `table_alias->aggregate_function_or_group_by_or_having_specified` has `GROUP_BY_SPECIFIED` bit set. At this time it won't be, so qualify_statement() is invoked on group_by_expression. In this invocation column reference is qualified i.e. a value_STATEMENT->COLUMN REFERENCE is converted to a column_alias_STATEMENT and the execution returns to qualify_query().
      * Since the column_alias belongs to outer query group_by_column_num or group_by_column_count is not set or incremented.
      * `table_alias->do_group_by_check` and `table_alias->aggregate_function_or_group_by_or_having_specified` is set at this time
    * We reach inner query's qualify_query() FOR loop, 2nd iteration (Where GROUP BY validation happens)
      * When we reach group_by_expression processing, it is checked whether `table_alias->do_group_by_checks` is set or not. It is so we do not further process GROUP BY clause
      * other clauses are processed and execution returns to qualify_query()
      * `table_alias->do_group_by_checks` is reset at this time
  * Consider outer query's qualify_query FOR loop, 2nd iteration
    * It calls qualify_statement() on the HAVING clause which has a subquery (again)
    * qualify_statement() invokes qualify_query() on the subquery
    * We reach inner query's qualify_query() FOR loop, 1st iteration (again)
      * We reach GROUP BY related processing code. At this time `table_alias->do_group_by_checks` is not set because of the reset that happened at the end of 1st qualify_query() call on inner query. Execution proceeds.
      * It is checked whether `table_alias->aggregate_function_or_group_by_or_having_specified` has `GROUP_BY_SPECIFIED` is set. It is as 1st qualify_query() invocation on inner query would have set this value and doesn't reset.
      * Because of this GROUP BY isn't further processed. If it was allowed to go past the check, then, qualify_statement() would have been invoked on the group_by_expression again and this time since already all the COLUMN_REFERENCE is replaced by column_alias_STATEMENT we would have reached column_alias_STATEMENT case where GROUP BY validation happens. Since we do not allow for further GROUP BY processing the validations doesn't happen.
      * If this second time processing is allowed then its possible to see that an outer query column reference exists in GROUP BY of inner query and if it is not part of outer query's GROUP BY an error can be issued.

Conclusion:
* Allow the second time processing which the last few points in the previous section talks about. This will solve the issue.

Alternatives considered and left because of various problems these approaches have:
1) GROUP BY clause needs to validate list items which has at least one entity belonging to outer query. Can some information about whether the list item belongs to outer query or not be used to selectively allow GROUP BY validations on particular list items? It is too much of a hassle to maintain information regarding whether an item in GROUP BY list has outer query element or not and the effort doesn't seem worth it.
2) Consider the execution context at _We reach inner query's qualify_query() FOR loop, 1st iteration_ in the above analysis section. Is it possible to invoke second time qualify_statement() on the GROUP BY clause column reference after it is qualified as a column_alias_STATEMENT? This approach isn't possible as well because of the scenario explained below
   * Why we cannot immediately call qualify_statement() to perform GROUP BY validation after an outer query column reference has been qualified in GROUP BY clause of inner query?
     * column_alias_STATEMENT case does GROUP BY validation based on `parent_table_alias->do_group_by_check` value. If this is not set the validation doesn't take place
     * Let say we set this value after qualification of the outer query column reference and modify the column_alias_STATEMENT case to allow GROUP BY validation on GROUP BY clause as well (by adding `AGGREGATE_DEPTH_GROUP_CLAUSE == parent_table_alias->aggregate_depth` to the condition) and then call qualify_statement(). In case if the subquery which is currently processing has the outer query column reference in the SELECT clause of the outer query, `group_by_column_num` will not be set and as a result we will end up issuing error even when we should not. Following is an example query which is expected to have a wrong output if the said change above is made.
    * Example:
      ```sql
       select exists(select 1 from names n2 group by n1.firstname) from names n1 group by firstname;
       ```
     * In the above query, 1st outer query, qualify_query() FOR loop
       * calls qualify_statement() on the SELECT list
       * qualify_query() on the subquery present in SELECT list is invoked
       * We reach 1st inner query, qualify_query() FOR loop
         * qualify_statement() on GROUP BY clause is called
         * value_STATEMENT -> COLUMN_REFERENCE case is reached
         * After qualification, value_STATEMENT is replaced with column_alias_STATEMENT
         * at that location itself we identify that the item belongs to outer query and parent_table_alias->do_group_by_check is not set. We set this value and then invoke qualify_statement on the column_alias_STATEMENT
         * We reach column_alias_STATEMENT case and here the GROUP BY validation IF condition includes `!column_alias->group_by_column_num`. This value is not set as outer query has not yet gone through qualification of its GROUP BY clause. Because of this an error is issued but this is incorrect. This is why this change is not made.

**Design**
* Let GROUP BY clause be processed even when `table_alias->aggregate_function_or_group_by_or_having_specified` has `GROUP_BY_SPECIFIED` bit set. This allows second qualify_query() call of inner query called from outer query's second iteration of qualify_query() FOR loop to process inner query GROUP BY clause. In such a case the outer query column reference will have its `parent_table_alias->do_group_by_checks` set, so column_alias_STATEMENT case in qualify_statement() can perform GROUP BY validations on the column references in GROUP BY clause of the inner query. This results in error issue for invalid cases as demonstrated in issue section.

**Change**
* Code to remove outer query columns in GROUP BY clause has been removed from qualify_query() as we need such columns during GROUP BY validation iteration of the outer query to issue error when the column is un-grouped. Instead, in the IF block which had this code we now have code to avoid incrementing `group_by_column_count` in case the column alias is an outer query column. Note qualify_statement() ensures that for the present query, `table_alias->group_by_column_count` is not incremented when an outer query column is processed in the present query's GROUP BY. This way the assert at the end of GROUP BY processing in qualify_query() `assert(group_by_column_count == table_alias->group_by_column_count);` remains valid.
* As above code change removed column removal logic, no columns from GROUP BY will be removed during qualify_query() invocation. But, there is a possibility of `group_by_column_count` value being 0 at the end of GROUP BY clause processing (because all GROUP BY clause items turned out to be outer query columns and above change ensured `group_by_column_count` was not incremented for such columns). In this case following code at the end of GROUP BY processing would have set `group_by_expression` to NULL, this is not desirable as we want the list to stay as it is for GROUP BY validation to happen on it. To avoid this problem following code is also removed.
  ```c
  if (!group_by_column_count) {
         select->group_by_expression = NULL;
  }
  ```
* outer query columns are still constants as far as inner query GROUP BY is considered so there exists a performance benefit to remove such column from GROUP BY clause. Because of this the removal is now done in generate_logical_plan(). This enables all validations to be done on GROUP BY clause as well as keeps the performance gain we had from removing outer query columns from GROUP BY.
* Next, since we do not need to validate current query columns in GROUP BY, the second iteration of FOR loop in qualify_query() still doesn't call qualify_statement() on GROUP BY clause. This is achieved by retaining `table_alias->do_group_by_checks` check before GROUP BY processing.
* But, outer query columns in inner query GROUP BY clause needs to go through GROUP BY validation. This means letting GROUP BY clause of the inner query go through qualify_statement() call even when `GROUP_BY_SPECIFIED` field of `aggregate_function_or_group_by_or_having_specified` is already set for the current `table_alias`. This is only possible when there are more than one levels of queries and when the qualify_query() call is from outer query's GROUP BY validation iteration.
* In order to allow such validations the second condition which was guarding qualify_statement() invocation on GROUP BY clause is removed. The disadvantage of this is that the GROUP BY clause goes through multiple qualify_statement() calls in case when a query has multiple levels. This is necessary to issue error when un-grouped column from outer query is used in inner query GROUP BY clause.
* Code in qualify_statement() which updates `group_by_column_num` and `group_by_column_count` is now set only if `GROUP_BY_SPECIFIED` bit of `table_alias->aggregate_function_or_group_by_or_having_specified` is clear. This way we avoid repeated modifications to `group_by_column_num` and `group_by_column_count` when the GROUP BY clause is going through GROUP BY validation from outer query.
* `ERR_UNGROUPED_OUTER_QUERY_COLUMN` error message is introduced in this change. This error specifically identifies un-grouped outer query column usage in inner query. Before this change, queries which had un-grouped outer query column usage in inner query would generate `ERR_GROUP_BY_AGGREGATE_FUNCTION` error. Because of the reasoning mentioned in https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1189#note_1065079443, `ERR_GROUP_BY_AGGREGATE_FUNCTION` was found to be confusing and hence, to better describe the reason for the failure, new error message (`ERR_UNGROUPED_OUTER_QUERY_COLUMN`) is introduced in this change. This error message is issued from `qualify_statement()->column_alias_STATEMENT` case. Before this change `column_alias_STATEMENT` case made use of `ISSUE_GROUP_BY_OR_AGGREGATE_FUNCTION_ERROR_AND_RETURN` macro to issue `ERR_GROUP_BY_OR_AGGREGATE_FUNCTION` error. Since same code can be used to issue the new error this macro is updated to include additional parameter which can be used to pass the error name to be displayed and the macro name is changed to `ISSUE_GROUP_BY_ERROR_AND_RETURN`. Its usage and related comments are  updated in `column_alias_STATEMENT` case block.

**Doc**
* doc/errors.rst is updated to include `ERR_UNGROUPED_OUTER_QUERY_COLUMN` error message

**Test**
* TGB35 is added to test this change
* TODO in TGB34.m related to this change has been addressed. While making the change it was found that the change mentioned in the TODO alone was not sufficient as `set groupby(depth)=""` was being executed unconditionally and because of this when random selection of GROUP BY column from different depth was done, the `groupby(depth)` would only be valid if the column selected belonged to the `depth` to which `groupby` LVN was set if it did not (which was the case as the selection was random) rest of the code (mainly the issue was found with aggregate function) would assume that the a column belonging to the depth exists in GROUP BY at that depth and use it as part of an aggregate expression. This leads to queries which result in un-grouped column reference error. So the code $$groupby was modified to set `groupby(depth)` only when the column chosen to be part of GROUP BY belonged to query at `depth` level.
* TGB19 was intended to test that an inner query select list column will generate GROUP BY error when its not in the inner query's GROUP BY and the GROUP BY has just one column belonging to outer query. With this change an error is issued for an un-grouped outer query column in GROUP BY, so the new error would have hidden what was being tested. To retain the original test intention the query was updated to make the outer query column in inner query GROUP BY a grouped column. This change results in testing whether a GROUP BY error is issued for the inner query's select list column which is not in its GROUP BY.
* TGB01.ref, TGB32_errors.ref, TGB33_errors.ref and TOB16_errors.ref were updated to reflect `ERR_UNGROUPED_OUTER_QUERY_COLUMN` addition

**Misc**
* Some grammar corrections are done in test_group_by.bats.in. These are not related to the issue being addressed.