[#710] SELECT queries fail with timeout if multiple clients connect to the same Rocto server process
Background
----------
This is an issue noticed by an Octo user. Below is a simple example demonstrating the issue.

* Create a function that hangs for `N` seconds where `N` is specified as a parameter (the `HANGTIME`
   function can be found at `tests/fixtures/HANGTIME.m`).

  ```sql
  $ octo
  OCTO> CREATE FUNCTION HANGTIME(VARCHAR, INTEGER) RETURNS VARCHAR AS $$^HANGTIME;
  OCTO> EXIT;
  ```

* Start a `rocto` listener at port 1338 in the background.

  ```sh
  $ src/rocto -p 1338 -vv > rocto.log 2>&1 < /dev/null &
  ```

* In terminal 1, start one psql client that runs a query which takes more than 10 seconds.
  The `12` usage below ensures the query will take at least 12 seconds to run.

  ```sh
  TERM1$ export PGPASSWORD=ydbrocks; psql -h $HOST -p 1338 -U $user
  nars=# SELECT HANGTIME(firstname,12) FROM names LIMIT 1;
  ```

* Immediately after starting the query in Step 3, in another terminal 2, start another psql client
  that runs a simple query that should return right away. This currently fails with a timeout after 10
  seconds of wait.

  ```sh
  TERM2$ export PGPASSWORD=ydbrocks; psql -h $HOST -p 1338 -U $user
  nars=# SELECT 1;
  ERROR:  YottaDB error: ydb_lock_s()/ydb_lock_incr_s() call timed out likely due to a concurrent long-running query.
  ```

* And below is the error message in the rocto log.

  ```sh
  [ERROR] src/run_query.c:154 ... : ERR_YOTTADB : YottaDB error: ydb_lock_s()/ydb_lock_incr_s() call timed out likely due to a concurrent long-running query.
  ```

* The issue is that multiple clients connecting to the `same` rocto listener server end up unintentionally
  going through the same query lock because the rocto processes serving the clients are all children of the
  `same` rocto listener server and end up taking a shared lock using the process id of the parent listener
  rocto process. Hence only one client query can be running at any point in time and if a query takes more
  than 10 seconds to get the lock due to long running client queries, one gets a timeout failure message.

Fix
---
* The fix is simple. And that is to set the `config->process_id` variable to point to the rocto server
  process right after the rocto listener process does a `fork()`. This is the pid that gets used later
  when we take a shared query lock in `run_query.c`. And this ensures multiple rocto processes take different
  locks and in turn do not affect each other for `SELECT` queries.

* A new `test_psql_connection/TPC026` bats subtest verifies this fix.