[#1069] Add tests to validate the change to handle NULL computed expression by `COMPEXP` in YDBOctoVistA
A user reported this error:

```
Error: ERROR: YottaDB error:
151027986,WARD+6^DGPMUTL,%YDB-E-ZYSQLNULLNOTVALID, $ZYSQLNULL cannot be used as an integer, numeric, gvn subscript/value or lock subscript
SQLState:  XX000
ErrorCode: 0
```

A sample query that would cause the error on VEHU Image:

```sql
SELECT
p.primary_long_id AS "MRN",
p.name AS "Patient Name",
pm.ward_at_discharge AS "Ward at Discharge",
COALESCE(CAST(pm1.date_time AS TEXT),'0') AS "Admission Date",
pm1.length_of_stay AS "Length Of Stay",
fmt.name AS "Movement Type"
FROM patient AS p
LEFT JOIN patient_movement AS pm on p.patient_id = pm.patient
LEFT JOIN patient_movement AS pm1 on pm.admission_check_in_mov = pm1.patient_movement_id
LEFT JOIN facility_movement_type AS fmt ON pm.type_of_movement = fmt.facility_movement_type_id
LEFT JOIN mas_movement_tran_type AS mmtt ON pm.transaction = mmtt.mas_movement_tran_type_id;
```

The reason for the failure is addressed by
https://gitlab.com/YottaDB/DBMS/YDBOctoVistA/-/merge_requests/41.
Refer to its commit message for more details.

This commit adds the test TVD0013 for this condition, to verify the fix.