[#915] Pre-compile Java and other refactoring
When we run the tests in parallel, Java tests would rarely fail with
this error message:

```
Error: LinkageError occurred while loading main class
run_multiple_query_files
        java.lang.ClassFormatError: Truncated class file
```

This error happened in `tests/test_helpers.bash.in` here:
```
>>	if [[ ! -e @PROJECT_BINARY_DIR@/$1.class ||
		$(stat -c '%Y' @PROJECT_BINARY_DIR@/$1.class) -le $(stat -c '%Y' @PROJECT_SOURCE_DIR@/tests/fixtures/$1.java) ]]; then
		# Copy .java file from fixtures directory to current directory to create .class file
		cp @PROJECT_SOURCE_DIR@/tests/fixtures/$1.java @PROJECT_BINARY_DIR@
		# Compile the .java file to a .class file
>>		javac @PROJECT_BINARY_DIR@/$1.java	# will create the file $1.class

	fi
```

While once test was compiling the .java code, another test presumed it
was compiled (the if check) and proceeded to use the file, resulting in
the error message.

This is now fixed by pre-compiling the Java files during the build step
in CMake using CMake Java instrinsic support.

While doing this, a few other miscelleanous refactoring was done:

- `test_jdbc_connection` was incorrectly thought to be the only test
  that needed Java. That's not true, as Java is used in various tests
  throughout the test system. So now Java is required whenever we want
  the FULL_TEST_SUITE.
- The Test systems currently requires two extra set-ups that should not
  be necessary for somebody just following the instructions. So the
  ultimate objective is that `make test` should work without any extra
  set-ups. The two set-ups are:
  - A YottaDB database for `handle_password_message`
  - Downloading a specific Postgres JDBC driver version, and manually
    exporting an environment variable.
  This latter step is now removed; instead, CMake downloads the
  requested version during configure time; and JDBC_VERSION is now
  maintained in ONE single location in `cmake/bats-tests.cmake`.

`build.sh` still has the old JDBC_VERSION logic for use by prior commits
in the auto-upgrade tests.