[#1096] Fix Clang 17 and GCC 14 compilation errors
Clang 17
--------
* Bison generated code warnings:
  ```
  physical-parser.c:841:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
  841 |     int yynerrs = 0;
      |         ^
  parser.c:3683:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
  3683 |     int yynerrs = 0;
       |         ^
  ```

  Caused by https://github.com/akimd/bison/issues/89. While the code was
  fixed, according to https://github.com/akimd/bison/issues/103, no
  upcoming release is planned to be made soon due to the lack of a
  maintainer.

  Fixed by setting `-Wno-unused-but-set-variable` on BISON output.

  `src/CMakeLists.txt` rearranged so that `BISON_TARGET`'s and
  `FLEX_TARGET`'s are placed close together.

* Strict prototype warnings (second example is repeated 2 more times in other files):
  ```
  In file included from src/history.c:24:
  /usr/include/readline/readline.h:411:23: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
    411 | extern int rl_message ();
        |                       ^
        |                        void
  In file included from src/parse_startup_flags.c:22:
  /usr/local/lib/yottadb/r203/gtmxc_types.h:79:78: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
     79 | void            gtm_start_timer(ydb_tid_t tid, ydb_int_t time_to_expir, void (*handler)(), ydb_int_t hdata_len, void *hdata);
        |                                                                                        ^
        |                                                                                         void
  ```

  Readline library issue fixed in latest Readline source code (manually checked). But older deployed versions are beyond our control.

  `gtmxc_types.h` is our code but cannot be easily fixed. Discussion at https://gitlab.com/YottaDB/DB/YDB/-/merge_requests/1785#note_2916104740.

  These are fixed using a fancy compiler directive documented here: https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas

  Import of `gtmxc_types.h`, since it's done 3 times, is passed to an intermediate header file.

GCC 14
------
* `src/history.c` had a `calloc` with flipped arguments.
  ```
  [3/42] Building C object src/CMakeFiles/libocto.dir/history.c.o
  src/history.c: In function ‘set_readline_file’:
  src/history.c:206:45: warning: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
    206 |         readline_actualfile = calloc(sizeof(char), readline_actualfile_max_length);
        |                                             ^~~~
  /home/sam/work/gitlab/YDBOcto/src/history.c:206:45: note: earlier argument should specify number of elements, later size of each element
  ```

  Fixed by taking compiler suggestion.