[#502] Ensure INSERT INTO queries are wrapped inside TSTART/TCOMMIT fence for ACID properties
Background
----------
* What if a query returns multiple rows and there is say a `VARCHAR_TOO_LONG` error while inserting
  one of those rows midway in the `INSERT INTO`? Will the first few rows that were inserted before
  the mid-way error be undone or will they remain?

  The answer is that there should be no rows inserted if an error occurs mid-way. It should be an
  atomic transaction. As the below behavior of Postgres illustrates. The first row will insert fine,
  but the second row will encounter an error.

  ```sql
  names=> CREATE TABLE test1 (id INTEGER PRIMARY KEY, column1 VARCHAR(3));
  names=> insert into test1 VALUES (1, 'abc'), (2, 'abcd'), (3, 'ab');
  ERROR:  value too long for type character varying(3)
  names=> select * from test1;
  id|column1
  (0 rows)
  ```

  If the above is run with Octo, one sees the `select * from test1` return 1 row (`1|abc`).
  This means even though the `INSERT INTO` encountered an error while inserting the 2nd out of 3 rows,
  at the end the 1st row made it through to the database. This is not correct.

* Towards this, Octo/Rocto now wrap all their query execution inside a `TSTART`/`TCOMMIT` fence.
  This ensures that we automatically inherit the ACID properties associated with a transaction fence.

Fixes
-----
* `src/aux/_ydboctoselect.m` : The main change is in this file where we surround the query execution
  with a `TSTART`/`TCOMMIT` (aka `TP`) fence.

  While in this, did some unrelated cleanup. Removed an unnecessary `filename` parameter which had
  implications in the following files.
  - src/aux/ydbocto.ci
  - src/rocto/handle_execute.c
  - src/run_query.c

* Because of the above `TSTART`/`TCOMMIT` change, the logic that redirected the `$ZTRIGGER()` output in
  `dollarZTRIGGER` entryref in `src/aux/_ydboctoplanhelpers.m` no longer worked. This is because in case
  of `TP`, the `$ZTRIGGER()` output is not flushed right away but buffered and accumulated until `TCOMMIT`
  at which time all accumulated output is sent to the `stderr` device.

  This caused lots of bats test failures because `octo`/`rocto` now issued a message like the following
  whenever executing queries that implicitly built cross-references.

  ```
  Added SET and/or Non-SET trigger on ^names named %ydboctoTOMMMsQ8ks3NI1C42wS8
  ```

  This required an enhancement in the YDB repo (YottaDB/DB/YDB#664). As a result, it now supports a
  `VIEW "ZTRIGGER_OUTPUT"` command that allows one to disable the output from `$ZTRIGGER`. This command
  is now added to `octo`/`rocto` startup in the file `src/aux/_ydboctoInit.m`.

  As a result, `src/aux/_ydboctoplanhelpers.m` is now greatly simplified. There is no more need for the
  `/dev/null` redirection.

  The above changes required a slight line number change in `tests/outref/TERR001.ref`.

* The `test_insert_into/TII05` bats subtest is enhanced to incorporate the test case described in the
  `Background` section above.

* Because we are now inside `TP` when a query is canceled, `src/aux/_ydboctoCleanup.m` (which is invoked
  when a query is canceled to return control back to `src/run_query.c`) needed a `TROLLBACK`.  The
  `test_cancel_request/TCR01` bats subtest failed without this change.

* Because we are now inside `TP` when a query is canceled, the `test_cancel_request/TCR03` bats subtest
  failed with a `TRANS2BIG` error before the cancel point was reached in the test. This necessitated bumping
  the number of global buffers from `1024` (default value) to `4096` in `tests/test_cancel_request.bats.in`.

* Note that this commit only involves wrapping `INSERT INTO` and `SELECT` inside `TP`. And only tests
  `INSERT INTO`. Other query operations like `DISCARD ALL`, `CREATE TABLE` etc. also need similar
  wrapping and automated test cases. And `SELECT` needs an automated test case to verify `TP` wrapping.
  All of this will be implemented in future commits.

* `src/rocto.c` had a cosmetic change (mismatched comment styles in same line).

* `src/m_templates/tmpl_print_expression.ctemplate` : Removed a TODO that was introduced in a prior commit
  (5b08cc0b9fd5f61f2ed733460e470db8f9550f8a) but had already been taken care of in the same commit.