[#828] Support column alias in GROUP BY
**Issue Description**

Column alias usages like the ones shown below should work
```sql
select firstname || 'x' as xyz, lastname || 'x' as lastname from names group by xyz, lastname || 'x';
select id as id1 from names group by id1;
```
At present, `ERR_UNKNOWN_COLUMN_NAME` error is issued for such usages.

**Design**

The implementation uses mostly ORDER BY alias related code in qualify_query(), `column_list_alias_STATEMENT` case of qualify_statement() and qualify_column_name() function. Additionally, qualify_column_name() is updated to handle ambiguity handling difference between ORDER BY and GROUP BY. Following explains the GROUP BY's working when a column alias name is ambiguous.

Below two conditions are implemented for GROUP BY column alias usage:
1) GROUP BY has different column alias association priority than ORDER BY. For example in the below query `firstname` is taken as the name of the table column and not the alias column. Where as in the ORDER BY alias example next to it, the query errors saying the column name is ambiguous.
   ```sql
   names=> select 'Zero' != 'Zero' as firstname,'test' as firstname from names group by firstname;
    firstname | firstname
   -----------+-----------
    f         | test
    f         | test
    f         | test
    f         | test
    f         | test
   (5 rows)

   names=> select 'Zero' != 'Zero' as firstname,'test' as firstname from names order by firstname;
   ERROR:  ORDER BY "firstname" is ambiguous
   LINE 1: ...firstname,'test' as firstname from names order by firstname;
                                                                ^
   ```
   In case of such ambiguity, GROUP BY name will be interpreted as an input-column name rather than a select list column name with this change. Note even if multiple columns in select list have same alias names there is no ambiguity error issued if an input column i.e. a column in the table from query's FROM clause has the same name as the alias name. For more details refer to discussion in https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1140#note_1003010368.

2) If the alias name doesn't match any input column i.e. a column in the FROM clause, then if ambiguity exists between select list column alias names an error is issued for the ambiguous alias usage in GROUP BY. Below example demonstrates the behavior.
   ```sql
   OCTO> select 'Zero' != 'Zero' as firstname,'test' as firstname group by firstname;
   [ERROR]: ERR_AMBIGUOUS_COLUMN_NAME: Ambiguous column name 'FIRSTNAME': qualify name for safe execution
   LINE 1: ... != 'Zero' as firstname,'test' as firstname group by firstname;
                                                                   ^^^^^^^^^
   ```

**Test**
1) TGB30 subtest is added to test_group_by.bats.in to verify the issue's working.

**Misc**
1) During refactoring ORDER BY code to process alias number some code and comment related to column number processing were also updated as both now are used by GROUP BY as well. During this change it was found that a column number which is larger than an `INTEGER` when used in GROUP BY issues an `ERR_ORDER_BY_POSITION_NOT_INTEGER` error which wasn't correct. This is updated now to issue ERR_GROUP_BY_POSITION_NOT_INTEGER (newly added) error instead. TGB21_errors.sql and TGB21_errors.ref are updated to validate this usage.