[#772] Issue ERR_DROP_FUNCTION_DEPENDS error if CHECK constraint in table relies on dropped function
Background
----------
* Below is the test case that we want to work in Octo just like it does in Postgres.
  In this test, we define a CHECK constraint on a table that relies on a function.  And then attempt
  a DROP FUNCTION. That errors out because the function is being relied upon by the CHECK constraint.
  Later we drop the table containing the constraint and then retry the DROP FUNCTION. This time it
  succeeds because there is no other object that depends on this about-to-be-dropped function.

  ```sql
  names=> CREATE FUNCTION SAMEVALUE(integer) RETURNS integer AS 'select $1;' LANGUAGE SQL IMMUTABLE;
  CREATE FUNCTION
  names=> CREATE TABLE products (
        product_no integer,
        name text,
        price numeric CONSTRAINT name1 CHECK (price * samevalue(product_no) < 1000)
    );
  CREATE TABLE
  names=> DROP FUNCTION SAMEVALUE(integer);
  ERROR:  cannot drop function samevalue(integer) because other objects depend on it
  DETAIL:  constraint name1 on table products depends on function samevalue(integer)
  HINT:  Use DROP ... CASCADE to drop the dependent objects too.
  names=> DROP TABLE products;
  DROP TABLE
  names=> DROP FUNCTION SAMEVALUE(integer);
  DROP FUNCTION
  ```

Implementation
--------------
* The high level plan is to note down all the functions that are used inside each constraint as part
  of a `CREATE TABLE` command. And store it in global variable nodes.

* Towards that, it seemed logical to enhance `qualify_check_constraint.c` to note down each function, as it is
  encountered while parsing the CHECK constraint, in an lvn of the following form.
  ```
  %ydboctoTblConstraint("functions",FUNCTION_HASH)=FUNCTION_NAME
  ```

* But turns out this is not enough, since we also need to note down the `name` of the constraint that uses
  this function as this is needed to later issue the error. But at the time `qualify_check_constraint()` is
  called, we have not yet determined the constraint name.

* Therefore, we note down the pointer to the constraint definition (an 8-byte pointer on 64-bit systems
  and a 4-byte pointer on 32-bit systems) as the name of a constraint and use this as a subscript in the lvn.
  The below lvn is therefore what gets stored.
  ```
  %ydboctoTblConstraint("functions",CONSTRAINT_POINTER,FUNCTION_HASH)=FUNCTION_NAME
  ```

* In addition, `qualify_check_constraint.c` needs to know which constraint is currently being processed.
  To help with that, `table_definition.c` records the currently processed constraint-pointer in the following
  lvn.
  ```
  %ydboctoTblConstraint("functions")=CONSTRAINT_POINTER
  ```

* And finally we need to know which constraint pointer maps to which constraint name. Towards that the
  following lvn is maintained in `table_definition.c`.
  ```
  %ydboctoTblConstraint("functions_map",CONSTRAINT_POINTER)=CONSTRAINT_NAME
  ```

* Once `table_definition.c` is done parsing all CHECK constraints, the goal is then to move the lvns
  created above into the below gvn structure in `store_table_in_pg_class.c`.
  ```
  ^%ydboctoocto("functions",FUNCTION_NAME,FUNCTION_HASH,"check_constraint",TABLE_NAME,CONSTRAINT_NAME)=""
  ^%ydboctoocto("tableconstraint",TABLE_NAME,CONSTRAINT_NAME,FUNCTION_NAME,FUNCTION_HASH)=""
  ```

* The first of the above gvns is enough for `DROP FUNCTION` to issue the needed error. A new
  `ERR_DROP_FUNCTION_DEPENDS` error is issued in case nodes under the following gvn subtree exist as that
  means we have at least one CHECK constraint for one table that is relying on the function FUNCTION_NAME
  with the hash FUNCTION_HASH.
  ```
  ^%ydboctoocto("functions",FUNCTION_NAME,FUNCTION_HASH,"check_constraint",*)
  ```

* The second of the above gvns is needed so a `DROP TABLE` knows to delete that first gvn node which is
  related to the table (and its CHECK constraints) being dropped. This will enable a later `DROP FUNCTION`
  to no longer issue the `ERR_DROP_FUNCTION_DEPENDS` error if tables containing all the dependent constraints
  of this function have been dropped.

  That is, all nodes under the following gvn node `^%ydboctoocto("tableconstraint",TABLE_NAME,*)` need to be
  examined to see what functions this table depends on and delete both sets of the gvn nodes for each found gvn.
  This logic is implemented in `src/aux/_ydboctoDiscard.m`.

Test
----
* The existing file `tests/fixtures/TCTC003.sql` has been enhanced with a test for the new
  `ERR_DROP_FUNCTION_DEPENDS` error.

Misc changes
------------
* A TODO in `src/decompress_statement.c` has been addressed by removing that block of comment and
  instead adding `#ifndef NDEBUG` code (i.e. code that executes only in a Debug build of Octo) that
  asserts that if a function is encountered in a CHECK constraint at `compress_statement.c` time, it
  continues to point to a valid/existing function even at `decompress_statement.c` time. Without the
  rest of the changes in this commit, this newly added assert used to fail when the enhanced
  `TCTC003.sql` test case (to test the `ERR_DROP_FUNCTION_DEPENDS` error) was run. But with the
  rest of the changes in this commit, this newly added assert does not fail.