Fix test_psql_connection/TPC007 subtest failure on Ubuntu 20.04 due to psql output format differences
* On a Ubuntu 20.04 system, `psql (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)` is the installed version
  of psql. With that version, I noticed the `test_psql_connection/TPC007` subtest fail with the following diff.

  ```diff
  1c1
  < FATAL:  Server requires all connections to be TLS encrypted. Please re-connect using a client with TLS/SSL enabled.
  ---
  > error: FATAL:  Server requires all connections to be TLS encrypted. Please re-connect using a client with TLS/SSL enabled.
  ```

* There is an extra `error: ` prefix in the line.

* Turns out this is due to psql adding that prefix. Since we don't see this failure in the pipeline which
  runs Ubuntu 18.04 and an in-house system that runs Ubuntu 21.10, I suspect this extra output is specific
  to the version of psql in a Ubuntu 20.04 system.

* The actual output from the `psql` invocation in the TPC007 subtest in a Ubuntu 20.04 system is the following.

  ```
  psql: error: FATAL:  Server requires all connections to be TLS encrypted. Please re-connect using a client with TLS/SSL enabled.
  ```

* The test script already strips out the `psql: ` prefix.

* So this commit strips out any other psql-version-specific prefixes (like `error: `) out by removing all
  strings until the `FATAL: ` keyword is seen.

* In addition, this commit stores the `psql` command output in a file `psql.out` just in case it is later
  needed for analysis of a rare test failure. Previously, the output was piped to the `sed` command which
  made it difficult to analyze test failures.

* For the record. The actual output from the `psql` invocation in a Ubuntu 18.04 system is the following.
  Notice the extra 3 lines before the line containing the `FATAL:` string whereas a Ubuntu 20.04 system
  has only 1 line of psql output as pasted in the previous bullets.

  ```
  psql: error: could not connect to server: Connection refused
          Is the server running on host "localhost" (::1) and accepting
          TCP/IP connections on port 1340?
  FATAL:  Server requires all connections to be TLS encrypted. Please re-connect using a client with TLS/SSL enabled.
  ```

  This is the reason why one needs to grep the `FATAL` string in the output and only include that line
  in the reference file to keep the output deterministic.