[#881] Disallow invalid string to integer or numeric casts
**Issue**

Cast usages shown below represent a set of error cases where it doesn't make sense to cast the source value to destination type and as a result should issue an error. At present such usages are allowed by the parser and M code determines its result. This behavior needs to be corrected to  validate the input before the actual conversion takes place such that all of the below cases will result in an error.
```sql
-- Following should generate an error but they don't
OCTO> select (select 'a'||'b'):: integer;
???
0
(1 row)

OCTO> select 'ab'::integer;
???
0
(1 row)
OCTO> select '1.0'::integer;
???
1
(1 row)
OCTO> select 't'::integer;
???
0
(1 row)
OCTO> select 'f'::integer;
???
0
(1 row)
```

**Analysis**
* It was found this issue mainly concerns with String to Integer and String to Numeric conversion.
* It is necessary for the validation to be done at run time as the input string value itself may be formed from an expression whose result we won't know until the expression is evaluated.
* An M routine which validates an input can be included in `src/aux/_ydboctoplanhelpers.m` and this routine can be called before the actual conversion to issue an error when input is invalid
* Other than the above point it was found that `NUMERIC` to `BOOLEAN` conversion and conversion the other way issues an error in Postgres. Since the type of an input can be determined by populate_data_type(), it is possible to have a check at `COERCE_TYPE` case statement to issue an error for conversion between `NUMERIC` and `BOOLEAN`.
* Note that String to `BOOLEAN` cast where String has a numeric value or invalid value is already handled so no need of any changes for it. The code which handles it can be seen at `$$String2Boolean^%%ydboctoplanhelpers`.

**Changes**
* ValidateInputAndGetTrimVal() is introduced to `src/aux/_ydboctoplanhelpers.m` to perform the validation. Note this routine also trims leading white space characters as these effect the actual conversion (string to integer conversion using `\` operator and string to numeric conversion using `+` operator). Trailing white spaces was found to not effect the conversion so it was left alone. Following describes the various conditions applied by the routine.
  ```
  ; The function checks whether the passed `value` is compatible for an INTEGER/NUMERIC cast or not.
  ; If the input `value` is found to be invalid, `IssueInvalidInputSyntaxError` is invoked to issue type specific error.
  ; `type` is expected to determine the conditions to find invalidity.
  ;  The following conditions are ensured to be TRUE by the routine
  ; 1. Input doesn't have only '+' or '-' alone in input string i.e. '+', '+  '  +',..
  ; 2. Input doesn't have period alone in the input string i.e. '.', '.  ',' .',..
  ; 3. Input doesn't have just white spaces i.e. '            '
  ; 4. Input doesn't have non integer or numeric characters in the input string i.e. 'abc','1.abc','1. 1',..
  ; 5. Input doesn't have period when the conversion is to an integer
  ; 6. Input doesn't have '+' or '-' where it is not expected i.e. '123+','12+2',..
  ```
* IssueInvalidInputSyntaxError() is introduced to `src/aux/_ydboctoplanhelpers.m` to issue `INVALIDINTEGERSYNTAX` or `INVALIDNUMERICSYNTAX` error based on the passed type value.
* `src/aux/_ydboctoInit.m` is updated to account for the new error additions listed in previous point
* `INVALIDINTEGERSYNTAX` issues `ERR_INTEGER_SYNTAX` error (Without current change). `INVALIDNUMERICSYNTAX` issues `ERR_NUMERIC_SYNTAX` error and is newly created in this change. `doc/errors.rst` and `src/errors.hd` has been updated to account for this new addition.
* String to Integer conversion is now done through another M routine which is introduced in this change to `src/aux/_ydboctoplanhelpers.m`. This routine was introduced in order to invoke validation related routine without having to handle dot additions during M plan generation.
* Similarly, String to Numeric conversion is carried out by another M routine which is introduced in this change to `src/aux/_ydboctoplanhelpers.m`. This helps to avoid dot count related additional handling.
* Numeric to Boolean conversion is considered invalid by Postgres and same behavior is implemented by this change. The following query demonstrates the expected behavior.
  ```sql
  names=> select 1.32::bool;
  ERROR:  cannot cast type numeric to boolean
  LINE 1: select 1.32::bool;
                     ^

  names=> select '1.32'::bool;
  ERROR:  invalid input syntax for type boolean: "1.32"
  LINE 1: select '1.32'::bool;
                 ^
  ```
* String to boolean conversion test above already works in Octo because of a runtime check in in `String2Bool` M routine. The case of `Numeric` to `Bool` conversion can easily be detected at populate_data_type() itself so additional validation for such conversion is added in populate_data_type(). With this change numeric to boolean conversion issue an error in Octo.
* During this change it was discovered that ABS return type for both `NUMERIC` and `INTEGER` input was `NUMERIC`. Because of this following query started issuing error in Octo saying the the input is invalid for a cast operation. This didn't seem correct. Taking a look at the octo-seed.sql file revealed that ABS definition for both `INTEGER` and `NUMERIC` type had `NUMERIC` return type. Because of this populate_data_type() ends up issuing the error.
  ```sql
  OCTO> select ABS(1)::bool;
  [ERROR]: ERR_INVALID_INPUT_SYNTAX: Invalid input syntax : Expecting type NUMERIC or INTEGER : Actual type NUMERIC
  ```
* In order to correct this behavior, ABS return type is changed from `NUMERIC` to `INTEGER` in case input is of type `INTEGER`. Following tests were used to confirm that this change was okay.
  ```sql
  names=> select abs(4)::bool;
   abs
  -----
   t
  (1 row)

  names=> select abs(1.4)::bool;
  ERROR:  cannot cast type numeric to boolean
  LINE 1: select abs(1.4)::bool;
                         ^
  ```
* Note that having return type as `NUMERIC` for both definition of ABS in octo-seed.sql results in the return type in cast operation in both the above queries to be NUMERIC which seems incorrect as an ABS of an `INTEGER` should be an `INTEGER`. Further testing as shown below revealed that this is not TRUE for other sql functions we have defined for example consider `ROUND`. `ROUND` can be used on `NUMERIC` as well as `INTEGER` type but both result in `NUMERIC` output as confirmed by the error seen below
  ```sql
  names=> select round(1.5,0)::bool;
  ERROR:  cannot cast type numeric to boolean
  LINE 1: select round(1.5,0)::bool;
                             ^
  names=> select round(1,0)::bool;
  ERROR:  cannot cast type numeric to boolean
  LINE 1: select round(1,0)::bool;
                           ^
  ```
* Other than `ROUND` function `TRUNC` also demonstrates similar behavior which lead to the conclusion that only ABS required this updated. Following are error cases which demonstrated that only ABS requires the return type change.
  ```sql
  names=> select TRUNC(1,0)::bool;
  ERROR:  cannot cast type numeric to boolean
  LINE 1: select TRUNC(1,0)::bool;
                           ^
  ```
* ABS definition in `octo-seed.sql` is updated to have return type of `INTEGER` instead of `NUMERIC` in case where the input type is also `INTEGER`
* `ERR_TYPE_CAST_TABLE_ASTERISK` is updated to `ERR_TYPE_CAST` as this error message is now issued for both TABLE.ASTERISK conversions and conversions between BOOLEAN and NUMERIC types in populate_data_type(). This error message takes in types as inputs so the final message seen will indicate what type of conversion was taking place.
* `NUL_VALUE` case block is removed from src/m_templates/tmpl_print_expression.ctemplate -> COERCE_TYPE case block as this value is not possible for cast operation. Also assert statements have been placed in COERCE_TYPE case block to ensure new types are identified.
* Renamed `INVALIDINPUTSYNTAXBOOL` to `INVALIDBOOLEANSYNTAX` to be consistent with `INVALIDINTEGERSYNTAX` etc.
* Renamed `ERR_INVALID_INPUT_SYNTAX_BOOL` to `ERR_INVALID_BOOLEAN_SYNTAX` to be consistent with `ERR_INVALID_INTEGER_SYNTAX` etc.
* @nars1 identified that a query such as `select 1::numeric(2);` would go through 2 sets of conversion calls internally. This was found as not necessary and has been updated to have just 1 conversion related M routine call. The code which was changed is src/m_templates/tmpl_print_expression.ctemplate->COERCE_TYPE case block-> NUMERIC_TYPE sub case block. More details regarding this topic can be found in https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1206#note_1102564633.
* `FMT_PLAN_DEFINITION` is bumped up by one. Its value was `20` and after this change will be `21`. This change was made because few plan names changed as the `ABS` function return type was changed from NUMERIC to INTEGER in this commit.

**Test Change**
* test_coerce_type -> TCT022 subtest is added to test_coerce_type.bats.in to validate this change. Several reference files in test_coerce_type.bats.in has been updated to account for the new error generation introduced in this change. The subtests whose reference files updated are - TCT000, TCT001, TCT003, TCT004, TCT009, TCT010, TCT011 and TCT012.
* test_coerce_type -> TCT000 -> The reference file is updated to reflect the changes in this commit which prevents invalid integer string to be converted to an integer using cast operation. The subtest intends to check  `coerce string to INTEGER` behavior, so this change doesn't deviate from what is being tested as it showcases the latest behavior of the tested conversion.  Also, additional valid query related to string to integer cast is added to make the test coverage have both the error case and the valid case. All double quoted strings were replaced with single quoted strings as the former's meaning was changing after !1182.
* test_coerce_type -> TCT001 -> The reference file is updated to reflect the changes in this commit which prevents numeric value in a string to be converted to an integer using cast operation. The subtest intends to check  `coerce canonical number string to INTEGER` behavior, so this change doesn't deviate from what is being tested as it showcases the latest behavior of the tested conversion. All double quoted strings were replaced with single quoted strings as the former's meaning was changing after !1182.
* test_coerce_type -> TCT003 -> The reference file is updated to reflect the latest behavior for converting a non numeric string to numeric. This is still coherent with the subtest intention as it just checks if coercing string to numeric works. After the update the latest behavior of such operation is recorded in the reference file. All double quoted strings were replaced with single quoted strings as the former's meaning was changing after !1182.
* test_coerce_type -> TCT004 -> All double quotes are replaced with single quotes as there meaning was changing after !1182. Because of this change the fixture could be now run through cross check function and it has been changed to do so. The double quotes were replaced with single quotes to represent strings as double quoted strings meaning was changing after !1182. Also, TCT004.ref is removed as it was no longer required.
* test_coerce_type -> TCT009 -> invalid integer cast related query output is updated to have error. This error is introduced in this change.
* test_coerce_type -> TCT010 -> `Cast2NUMERICWithoutPrecision` introduced in this change is replaces the `ForceNumeric` invocation in reference file. The former validates the input in addition to calling the later internally. Reference file is updated to reflect the new M routine.
* test_coerce_type -> TCT011 -> The change done updates the reference file content for few queries to show error instead of the original output. The change done in this commit removes the difference mentioned in the issue related to this subtest. Comment: https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/304#note_270726143. Test coverage isn't changed as even the updated query result in few cases confirm the cast operation working.
* test_coerce_type -> TCT012 -> From https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/300 description what could be gathered is that the result of both the queries in this subtest are expected to be same. With this change "1abcd" is considered to be an invalid input type for a numeric cast operation. Because of this an error was being issued for this query. Since the test being done is to validate the output seen when a calculated value is formed using cast operation, both "1abcd" and "1" could achieve the same purpose. Hence this test was updated to have "1" instead of "1abcd". Double quotes in the fixture were replaced with single quotes to represent strings as double quoted strings meaning was changing after !1182.
* test_coerce_type -> TCT013 -> Reference file is updated to have error message for invalid string to integer/numeric conversions instead of the original output. The change reflects the latest behavior of such conversions and since the test intended to validate such conversions, this change doesn't deviate from its original intention.
* test_boolean_type - TBT03 - A numeric value cannot be cast'd to a boolean value after this change. This behavior is same as Postgres. The test is updated to reflect this change. It is also updated to have ERR_INVALID_BOOLEAN_SYNTAX instead of ERR_INVALID_INPUT_SYNTAX_BOOL (renamed in this commit).
* test_select_columns -> TSC01 -> The original test was trying to cast `firstname` column of `names` table to `integer`. With the new changes this is not allowed. Since the test intention is to verify that strings can be cast'd to an integer, the query is modified to operate on a new table with column being strings whose conversions to integer is valid.
* test_errors -> TERR001 -> Error line number has changed in TERR001.ref due to new runtime error addition. The file is updated to reflect the new line number.
* test_group_by - TGB22 - new validation between incompatible conversion of string to integer or numeric resulted in this failure. The test case has been modified to have a valid query since the test intends to verify GROUP BY working rather than cast operation working. The change was to let parmlessfunc() be converted to VARCHAR instead of INTEGER or NUMERIC. The return value of parmlessfunc() is "SUCCESS" so INTEGER/NUMERIC conversions are expected to issue an error after this change.
* test_select_columns_psql - TSCP20 - #881 related query which previously existed in this test is now giving the expected result. The comment which asked to update the test after #881 changes has been removed.
* test_memory_usage - TMU02 - is updated because of new run time error additions. The error code changed and the reference file is updated to reflect the new changes. Also, the test is updated to have INVALIDBOOLEANSYNTAX instead of INVALIDINPUTSYNTAXBOOL (renamed in this commit).
* test_createtable - TC010 subtest failed because the conversion of a DATE or TIME column is received in tmpl_print_expression as a STRING_LITERAL type and STRING conversion to INTEGER or NUMERIC are additionally checked to have the right format with this change. The test reference was updated to have the error instead of its original output.
  * Following is a demonstration of what Postgres output looks like in this case.
  ```sql
    names=> CREATE TABLE DATETIME (id INTEGER PRIMARY KEY, date1 DATE, time1 TIME);
    CREATE TABLE
    names=> SELECT date1::integer from DATETIME;
    ERROR:  cannot cast type date to integer
    LINE 1: SELECT date1::integer from DATETIME;
                        ^
    names=> SELECT time1::integer from DATETIME;
    ERROR:  cannot cast type time without time zone to integer
    LINE 1: SELECT time1::integer from DATETIME;
                        ^
    names=> SELECT time1::numeric from DATETIME;
    ERROR:  cannot cast type time without time zone to numeric
    LINE 1: SELECT time1::numeric from DATETIME;
                        ^
    names=> SELECT date1::numeric from DATETIME;
    ERROR:  cannot cast type date to numeric
    LINE 1: SELECT date1::numeric from DATETIME;
                        ^
    ```
* test_createtable -> TC029 and TC033 -> Changes are due to the fact that ABS return type was updated from NUMERIC to INTEGER when the argument is of type INTEGER in octo-seed.sql
* test_create_function -> TCF019 and TCF022 -> Changes are due to the fact that ABS return type was updated from NUMERIC to INTEGER when the argument is of type INTEGER in octo-seed.sql
* test_seed_queries -> TSQ011 -> Changes are due to the fact that ABS return type was updated from NUMERIC to INTEGER when the argument is of type INTEGER in octo-seed.sql
* test_constraint_table_column -> TCTC003 - Changes are due to the fact that ABS return type was updated from NUMERIC to INTEGER when the argument is of type INTEGER in octo-seed.sql
* test_table_asterisk -> TTA003 -> ERR_TYPE_CAST_TABLE_ASTERISK to ERR_TYPE_CAST change resulted in updated of this subtest's reference file.
* test_null_keyword -> TNK01_errors.ref -> Is updated to have ERR_INVALID_BOOLEAN_SYNTAX instead of ERR_INVALID_INPUT_SYNTAX_BOOL (renamed in this commit).
* test_not_operator -> TNO02 -> Is updated to have ERR_INVALID_BOOLEAN_SYNTAX instead of ERR_INVALID_INPUT_SYNTAX_BOOL (renamed in this commit).
* test_select_subquery -> TSS01_errors.ref -> Is updated to have ERR_INVALID_BOOLEAN_SYNTAX instead of ERR_INVALID_INPUT_SYNTAX_BOOL (renamed in this commit).