[#1057] Fix [-Wuse-after-free] compiler warning in emit_physical_plan.c (regression in edfbcccb)
A newer version of GCC found the following warning in commit edfbcccb8ed9630657653688edf0b94b5daf0d48.

Compilation error in `src/physical/emit_physical_plan.c`:

```
/builds/YDBDBMS/src/physical/emit_physical_plan.c: In function ‘emit_physical_plan’:
/builds/YDBDBMS/src/physical/emit_physical_plan.c:362:14: warning: pointer ‘output_file’ used after ‘fclose’ [-Wuse-after-free]
362 |         fd = fileno(output_file);
  |              ^~~~~~~~~~~~~~~~~~~
/builds/YDBDBMS/src/physical/emit_physical_plan.c:357:9: note: call to ‘fclose’ here
357 |         fclose(output_file);
  |         ^~~~~~~~~~~~~~~~~~~
```

It's now fixed.