[#980] Correct error message format for parsing errors
Issue (copied from the description of #980)
-----
Error messages are inconsistent
```
OCTO> selegletct from * t;
LINE 1:1: selegletct from * t;
          ^^^^^^^^^^
syntax error, unexpected IDENTIFIER_ALONE
OCTO> select * from t;
[ERROR]: ERR_UNKNOWN_TABLE: Unknown table: T
LINE 1:1: select * from t;
                        ^
OCTO>
```

vs Postgres

```
names=> selegletct from * t;
ERROR:  syntax error at or near "selegletct"
LINE 1: selegletct from * t;
        ^
names=> select * from t;
ERROR:  relation "t" does not exist
LINE 1: select * from t;
                      ^
```

Octo should display [ERROR] before the query.

Analysis
------
* Bison passes error string `syntax error, unexpected IDENTIFIER_ALONE` string to yyerror() defined in src/yyerror.c
* yyerror() took care of printing the query details of the error message and the error string. Here the above string
  was printed after query information of an error message. The code which handles this needs to be fixed.

Fix
---
* src/yyerror.c is updated as follows
  * ERROR() instead of PRINT_YYERROR() is used. This helps to add error mnemonic to the error message. Previous to this change only the
    error message was being printed without mnemonic. When the query was from Rocto `CUSTOM_ERROR` mnemonic was added to log.
    Both now will have mnemonic `ERR_PARSE_FAILED`.
  * Ordering of the error message text was corrected to have ERROR line first and then the LINE information. Previously this was reverse.
* `ERR_PARSE_FAILED` is introduced in this commit to represent the syntax errors generated by Parser. src/errors.hd and doc/errors.rst is updated
  to add this ERROR message.
* With this change `INFO_TEXT_REPRESENTATION` and `ERR_PARSE_FAILED` will have the same message string. This was flagged by pre-commit hook with an
  error message saying both were duplicate. It was discussed offline and decided to allow this duplication for only these two error messages.
  More info on this is here -> https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/980#note_1990491478. tools/ci/doc_error_update.sh is updated
  for this reason. When the script comes across `xxx` `format_string` it checks whether it belongs to either of the error messages mentioned earlier
  and issues an error if the check fails. The error message that will be displayed is `Error message of $mnemonic is already used for
  ERR_PARSE_FAILED and INFO_TEXT_REPRESENTATION. Please change the message.`. The `$mnemonic` is replaced by the ERROR mnemonic
  which has `xxx` as `format_string`. Additionally, the script was updated to do perform multiple tests as explained in the following comment
  ```
  # If "check" is passed to this script as an argument then only missing_mnemonics and missing_messages checks are done
  # else missing_mnemonics, missing_text, duplicated_text and duplicated_xxx_text checks are done and missing text is added to
  # doc/errors.rst
  ```
* Several test reference files are updated to match the new error message ordering and content most of them are straight forward replacements
* Following are more info on some of the reference files changes. These didn't seem straightforward to understand hence more info:
  1. The SQLState change to `42601` in TSSCQ21.ref matches what is seen in Postgres for such errors after this change
     ```sql
     names=> \set VERBOSITY verbose
     names=> selegletct from * t;
     ERROR:  42601: syntax error at or near "selegletct"
     LINE 1: selegletct from * t;
             ^
     LOCATION:  scanner_yyerror, scan.l:1188
     ```
  2. tests/fixtures/TR22.exp -> ordering of message changed so this file is updated to expect the new order of messages