[#972] Issue error when regex operations use non-NULL non-STRING type values as operands
Issue (copied from issue description)
----
@nars1 discovered this behavior in Octo during review of !1244 . Octo allows comparisons with INTEGER type values using LIKE
operator. Postgres behavior is different in such a case. The operation is disallowed by generating an error. Following is
the sample query which demonstrated the difference.

Octo's output
```sql
OCTO> select * from names where id like 4::integer;
ID|FIRSTNAME|LASTNAME
4|Joey|
(1 row)
```

Postgres output
```sql
names=> CREATE VIEW v587 as select * from names where id like 4::integer;
ERROR:  operator does not exist: integer ~~ integer
LINE 1: CREATE VIEW v587 as select * from names where id like 4::int...
                                                         ^
```

Following cases need to be considered during implementation
* The operand here can be any type of `SqlStatement`
* Similar problem exists with `SIMILAR TO` as well
* Ensure all operations which go through regex_specification() are handled

Fix
----
* populate_data_type() calls binary_operation_data_type_check() to perform final validation of operand types in case of a binary
  operation.
* In this case LIKE, SIMILAR TO, ~~, ~* etc all are form `binary_STATEMENT`s so all go through this function
* Previously binary_operation_data_type_check() allowed all types of operands for REGEX operations. This is not expected, only
  string type operands are allowed for regex operations. Code in this function is modified to issue an incompatibility error
  when the operand type for a regex operation is not STRING or NULL.
* When special characters are not present in right operand of a regex operation the operation itself was being converted to
  EQUALS in src/parser/regex_specification.c. This was done by checking the right operand of the regex operation. In case the left
  operand has a non-STRING or non-NULL value then an error needed to be generated but as the operation is changed the validation that
  happens in binary_operation_data_type_check() failed to issue an error. After this change, code to perform this optimization
  is removed from src/parser/regex_specification.c and the responsibility of doing this operation is passed to
  binary_operation_data_type_check(). Code is added to binary_operation_data_type_check() to perform this optimization when the
  operand types are valid for a regex operation and if the right operand has no special characters.
  This allows binary_operation_data_type_check() to validate and issue incompatibility error when the operation is regex and
  operand is not string or NULL type.
* For the EQUALS optimization, regex_has_no_special_characters() is used to check if the operand is valid for the EQUALS
  conversion. Previously this function made use of IS_LITERAL_PARAMETER() to know if further processing can be done on the
  operand passed to it. After this change IS_STRING_TYPE() is used instead as regex_has_no_special_characters() can only
  analyze string literals to see if they point to a literal that is not a regex. It cannot analyze any other types of values
  (e.g. a COERCE_TYPE etc.) at query parse time (can only do it at query runtime).
* Since all regex operations are now handled by binary_operation_data_type_check() itself the regex operation related handling
  in src/validate_table_asterisk_binary_operation.c is removed. The removed code just checked for incompatibility of operand types.
  The new code also does the same. One difference is that the removed code had error message generation with `REGEX` text.
  The queries which went through the removed code path would have had `REGEX` in error message now it will have `regex` text
  instead. The text is updated to be more consistent with other such error message texts.
* After this change some of the queries which used to generate `ERR_TYPE_MISMATCH` generate `ERR_TYPE_NOT_COMPATIBLE`
  * This is better as `ERR_TYPE_NOT_COMPATIBLE` error code is same as Postgres's error code for such query failures
  * The error is generated by REGEX operation related checks in binary_operation_data_type_check() instead of EQUALS
    operation related checks. This is better since the operation which causes this error is REGEX.
* One consequence of moving the optimization handling from regex_specification() to binary_operation_data_type_check()
  is that if an expression like `('test' || 'test') NOT LIKE 'test'` is used then before this change this expression
  would have been converted to `('test' || 'test') != 'test'`, now it will be converted to `NOT(('test' || 'test') = 'test')`. This happens
  because we wait till the type is determined in binary_operation_data_type_check() to perform the optimization. Note even in this case when
  optimization is applied on the logical plan `NOT(('test' || 'test') = 'test')` is converted to `('test' || 'test') != 'test'`. Just that the
  additional step is done. Following is the difference seen in the initial logical plan. The optimized logical plan before and after this change
  is the same. TRTE09 validates the structure.
  ```
      39,44c39,43
      <             LP_BOOLEAN_NOT:
      <               LP_BOOLEAN_EQUALS:
      <                 LP_CONCAT:
      <                   LP_COLUMN_ALIAS: NAMES(1).FIRSTNAME
      <                   LP_COLUMN_ALIAS: NAMES(1).LASTNAME
      <                 LP_VALUE: 'test'
      ---
      >             LP_BOOLEAN_NOT_EQUALS:
      >               LP_CONCAT:
      >                 LP_COLUMN_ALIAS: NAMES(1).FIRSTNAME
      >                 LP_COLUMN_ALIAS: NAMES(1).LASTNAME
      >               LP_VALUE: 'test'
   ```

Test
----
* TRTE08 and TRTE09 is added to validate this fix
* TRTE07 reference file is updated as now operations such as 'asdf' LIKE 'asdf' will remain a LIKE operation
  and that is what is added to hash. Previously it was converted to EQUALS and that was being added to hash.
  The difference is hash is the change updated.
* TTA012_errors.ref is updated as operations such as table.* LIKE 'test' issue ERR_TYPE_NOT_COMPATIBLE instead of
  ERR_TYPE_MISMATCH. Similar change is done to TNK05.ref
* TWO14 subtest which previously verified an optimization for LIKE operation when using integer operation is updated
  to validate that error is issued for such use cases