[#759] Fix TABLENAME.ASTERISK issue in HAVING clause
Background
----------
* This is an issue with `HAVING` and `TABLENAME.ASTERISK` usage that I noticed.
  See https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/759#note_738472680 for more details.

* In the below query the `GROUP BY` is done on `n1.firstname` but we use `n1.*` inside the
  `HAVING` clause. There was no `GROUP BY` done on `n1.*` and so this query should have issued
  an error but Octo runs it fine. Postgres correctly issues an error.

  **Octo output**
  ```sql
  OCTO> select 1 from names n1 group by n1.firstname having n1.* IS NOT NULL;
  ???
  1
  1
  1
  1
  1
  (5 rows)
  ```

  **Postgres output**
  ```sql
  names=> select 1 from names n1 group by n1.firstname having n1.* IS NOT NULL;
  ERROR:  column "n1.*" must appear in the GROUP BY clause or be used in an aggregate function
  LINE 1: ...lect 1 from names n1 group by n1.firstname having n1.* IS NO...
                                                               ^
  ```

Fix
---
* The main fix is in `src/qualify_statement.c` to remove the `is_stmt_table_asterisk()` call.  This is
  because we should not be giving any exceptions to `table.*` column references. We should treat them
  just like we do regular column references. This would then automatically result in an error being
  issued if a `table.*` usage occurs in the `HAVING` clause but a `table.*` was not specified in `GROUP BY`.

  Also removed a comment block related to this call.

  A previous usage of `parent_table_alias->aggregate_function_or_group_by_specified` was removed and
  instead replaced with an assert that it would indeed be `TRUE` if `parent_table_alias->do_group_by_checks`
  (which is checked first in the `if` condition) is also `TRUE`.

* After the above fix, the following pre-existing query in `tests/fixtures/TTA003.sql` started to fail.

  ```sql
  OCTO> SELECT n1.* FROM names n1 GROUP BY n1.* HAVING n1.* IS NOT NULL;
  [ERROR] src/qualify_statement.c:78 2021-11-19 14:04:07 : ERR_GROUP_BY_OR_AGGREGATE_FUNCTION : Column N1.* must appear in the GROUP BY clause or be used in an aggregate function
  Error with syntax near (line 1, column 47):

  SELECT n1.* FROM names n1 GROUP BY n1.* HAVING n1.* IS NOT NULL;
                                                 ^^
  ```

  The reason for this failure is that the `n1.*` reference in the `HAVING` clause is treated as a different
  reference than the `n1.*` reference in the `GROUP BY`. This is now fixed by returning the same column alias
  for all `n1.*` references in `src/qualify_column_name.c`. This also meant a new `table_asterisk_column_alias`
  field in the `SqlTableAlias` structure.

Test
----
* The `test_tablename_asterisk/TTA003` subtest has been enhanced to verify this fix.

Misc
----
* The logic that expanded `*` usages in the SELECT column list in `src/qualify_query.c` was simplified.
  It used to be inside a `for` loop but executed only in the first iteration of the loop.
  So this is now moved outside the for loop.

* Took this opportunity to add/reword comments in various places.