[#346] Add test cases from #346
This does not close #346 because it does not re-enable the query
generator, because it creates incorrect queries:

```sql
boolean=> SELECT ALL alias1.available FROM stock_availability  INNER JOIN stock_availability AS alias1 ON ((stock_availability.available < alias1.available) OR (stock_availability.product_id < alias1.product_id)) WHERE ((stock_availability.available = stock_availability.available) AND NOT (stock_availability.product_id <= '') OR (stock_availability.available < ''));
ERROR:  invalid input syntax for integer: ""
LINE 1: ...ilable) AND NOT (stock_availability.product_id <= '') OR (st...
```

This should be fixed and the generator re-enabled in a follow-up MR.