[#786] Issue ERR_GROUP_BY_OR_AGGREGATE_FUNCTION error if ungrouped column is used in HAVING clause
Background
----------
* This is a day-one issue in the `HAVING` clause. If one uses an ungrouped column in that clause
  outside of an aggregate function, Octo currently does not issue an error whereas it should.
  See https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/786#description for more details.

* See simple query output below for example.

  **Octo output**
  ```sql
  OCTO> select 1 from names n1 having n1.firstname = 'Acid';
  ???
  1
  1
  1
  1
  1
  1
  (6 rows)
  ```

  **Postgres output**
  ```sql
  names=> select 1 from names n1 having n1.firstname = 'Acid';
  ERROR:  column "n1.firstname" must appear in the GROUP BY clause or be used in an aggregate function
  LINE 1: select 1 from names n1 having n1.firstname = 'Acid';
                                        ^
  ```

Fix
---
* The first change was to identify in `src/qualify_query.c` that we are qualifying the `HAVING` clause.
  This is done by noting down `table_alias->aggregate_depth` as a new `AGGREGATE_DEPTH_HAVING_CLAUSE`
  enum value. This way `src/qualify_statement.c` knows we are inside the `HAVING` clause.

* Next change was to notice that the `HAVING` clause cannot have `column_list_alias_STATEMENT` structures.
  All column references there would end up as `column_alias_STATEMENT` structures. This means that the
  `ERR_GROUP_BY_OR_AGGREGATE_FUNCTION` error that is currently issued in `src/qualify_statement.c` can
  never be issued for column references inside the `HAVING` clause. Therefore, it is unnecessary to
  keep the `qualify_statement(select->having_expression)` invocation in `src/qualify_query.c` inside
  the `for` loop (where the second iteration of the loop is to issue the `ERR_GROUP_BY_OR_AGGREGATE_FUNCTION`
  error. Therefore, this was moved out of the `for` loop.

* The next change was in `src/qualify_statement.c` inside the `COLUMN_REFERENCE` case. Here we now check
  if we are inside the `HAVING` clause. And if so, we see if the column reference is a non-grouped
  reference. If so we issue the `ERR_GROUP_BY_OR_AGGREGATE_FUNCTION` error.

* One last change is to ensure we do not incorrectly issue an error if the non-grouped column reference is
  done inside of an aggregate function. Towards this, when we notice an aggregate function in the `HAVING`
  clause in `src/qualify_statement.c`, we temporarily reset `table_alias->aggregate_depth` to `0` before
  entering the aggregate function `qualify_statement()` call. And set it back to `AGGREGATE_DEPTH_HAVING_CLAUSE`
  once we return from the function call. This way column references inside an aggregate function will not
  go through the new code (introduced for the previous bullet) and so will not issue an incorrect error.

Test
----
* The existing `test_group_by/TGB01` subtest was enhanced to verify this fix.

Misc
----
* A new `ISSUE_GROUP_BY_OR_AGGREGATE_FUNCTION_ERROR` macro is defined in `src/qualify_statement.c` to avoid
  code duplication since this error is now issued from multiple places.