[TEST-FRAMEWORK] Enhance portno.m to help find duplicate rocto portno allocation cause
* Commit 714b09b8 was the first step towards identifying the cause of portno conflicts. That is,
  multiple subtests that run concurrently choose the exact same portno and so the clients of
  those subtests talk to a rocto from the other subtest resulting in both the subtests failing.

* After that commit got merged, I got the below in-house cron job failure (which is similar to the
  failure that originally motivated the above commit).

  ```
  # ----------------------------------------------------------
  # List of failed tests/subtests and their output directories
  # ----------------------------------------------------------
  156/162 Test: test_date_time_type2
    not ok 12 TDTT096 : Validate that timezone seconds is generated and cross check function validates this output
    # Temporary files in: /builds/YDBDBMS/build/bats-test.6YSbeM
  143/162 Test: test_tablename_asterisk
    not ok 10 TTA010 : OCTO799 : TABLENAME.ASTERISK works with binary operation
    # Temporary files in: /builds/YDBDBMS/build/bats-test.o6VWGk
  # -----------------------------
  ```

* The TDTT096 subtest had the following failure output.

  ```
  #######################################
  # [cat TDTT096-1.octo.out.err] output follows
  psql: could not connect to server: Connection refused
  	Is the server running on host "localhost" (::1) and accepting
  	TCP/IP connections on port 1339?
  ERROR:  handle_password_message: failed to retrieve user info for user ydb from database
  ```

* The below is the output from `portno.out` of the 2 failed subtests.

  ```sh
  [root@49869514e7d2 build]# more bats*/portno.out
  ::::::::::::::
  bats-test.6YSbeM/portno.out
  ::::::::::::::
   2025-06-20T07:58:50,654826733-04:00 : Allocated port [1339]
   2025-06-20T07:58:52,244920724-04:00 : Released port [1339]
   2025-06-20T07:58:52,457818663-04:00 : Released port [1339]
  ::::::::::::::
  bats-test.o6VWGk/portno.out
  ::::::::::::::
   2025-06-20T07:58:50,905994480-04:00 : Allocated port [1339]
   2025-06-20T07:58:52,512152081-04:00 : Released port [1339]
  ```

* Notice how TDTT096 allocated port 1339 at `07:58:50,654826733` and released it only 2 seconds later
  but TTA010 allocated the same port at `07:58:50,905994480` before that 2 second period expired.

* The journal file introduced in 714b09b8 confirms that both the above subtests allocated portno 1339 at
  the exact same time as can be seen by the `67376,28730` value of the `SET` journal records seen below.

  ```
  0x00082810 [0x0070] :: SET    \67376,28730\882\...\^portdir(1339)="/builds/YDBDBMS/build/bats-test.6YSbeM/"
  0x00082a38 [0x0048] :: KILL   \67376,28730\883\...\^portdir(1339)
  0x00082c38 [0x0070] :: SET    \67376,28730\884\...\^portdir(1339)="/builds/YDBDBMS/build/bats-test.o6VWGk/"
  0x00082e60 [0x0048] :: KILL   \67376,28732\885\...\^portdir(1339)
  ```

* But there is an intermediate `KILL` record seen above at `67376,28730` for which there is no corresponding
  line in `portno.out` (i.e. there is no `Released port [1339]` line showing up at `07:58:50,...`.)

* So it is not clear what other subtest sneaked in between the 2 SET journal records and wrote the KILL
  record which is what made port 1339 available for reuse by TTA010 even though it was still not released
  by TDTT096.

* Towards finding that, more information has been added in this commit. The env var `BATS_TEST_NAME` holds
  the bats subtest that is currently running so that is used as well as the current test output directory
  and whether a find or release or scavenge port operation is happening and what time this happened in
  microsecond resolution (`$zut`). All this information is stored as subscripts and/or value of the node
  in the `^history` global variable.

  An example extract is shown below.

  ```
  ^history(1750444511906394,1344,"findopenport","/home/nars/work/github/YDBOcto/build/bats-test.PLZWys/")="test_TJC022_-3a_OCTO1041_-3a_Bind_parameter_test"
  ^history(1750444512686155,1344,"releaseport","/home/nars/work/github/YDBOcto/build/bats-test.PLZWys/")="test_TJC022_-3a_OCTO1041_-3a_Bind_parameter_test"
  ```

* This should hopefully give us more information as to which subtest sneaked in between and incorrectly
  made a portno available by doing a `KILL` of the `^portdir(1339)` node above.

* Given the previous failure happened on Jun 13 and this one is only 7 days later, I expect the next
  failure to happen in a week or two and hopefully figure the real cause of the portno conflict then.

* Because of the `^history` node changes in `portno.m`, the key-size of `find_open_port.gld` for the
  DEFAULT region had to be increased to allow for those long subscripts shown above (to avoid a
  GVSUBOFLOW error with the default key size of 64). The new key size is set at 1000, which is close
  to the design maximum and should be more than good enough.

* Similarly, the value of the `^history()` node can get quite long in some bats subtest cases. It was
  seen to get as long as `383` in the pipeline resulting in a `REC2BIG` error because the default
  max record size was `256`. Therefore, the new record size is set at 10,000 to avoid such rare failures.