[#609] Fix rocto to not require --allowschemachanges to run TRUNCATE commands
Background
----------
Below is the issue pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/609#note_1237854466

* I started `rocto` with the `-vv` option and used `psql` to connect to it and then ran a `TRUNCATE`
  command. I got an error that talked about `make schema changes`. This seems incorrect as a `truncate`
  is not making any schema changes.

  ```sql
  user=# truncate names;
  INFO:  Parsing done for SQL command [truncate names;]
  INFO:  Returning failure from run_query
  ERROR:  Rocto is not allowed to make schema changes without startup flag --allowschemachanges
  ```

  A `DELETE FROM` query, on the other hand, issued a more accurate
  `Cannot modify table due to read-only permissions` error as can be seen below.

  ```sql
  user=# delete from names;
  INFO:  Parsing done for SQL command [delete from names;]
  INFO:  Returning failure from run_query
  ERROR:  Cannot modify table: user 'user' has read-only permissions
  ```

  I expect the `TRUNCATE` to behave the same way as the `DELETE FROM`.

Issue
-----
* The `truncate_table_statement` grammar rule in `src/parser.y` was added under the
  `sql_schema_manipulation_statement` rule. This automatically made it a schema change operation
  and that is why `rocto` required `--allowschemachanges` to run `TRUNCATE` commands.

Fix
---
* The `truncate_table_statement` grammar rule is now placed under the `sql_data_change_statement` rule.
  This is where the similar operation `DELETE FROM` is defined (`delete_statement_searched` rule).

Tests
-----
* Due to the above code changes, `tests/test_truncate.bats.in` is now modified to use `--readwrite`
  instead of `--allowschemachanges` in the `start_rocto` command. This is because the latter is no
  longer necessary.

* The pre-existing `test_permissions` test is enhanced to test `TRUNCATE` wherever the test already
  tested `DELETE FROM` operations. This required changes to `tests/fixtures/TP001.sql` and
  `tests/fixtures/TP000.sql` to add a `TRUNCATE` command. But since these files are used by various
  subtests, it required changes to various subtest reference files in that test all of which verify
  `rocto` behavior in various test scenarios for `TRUNCATE` commands.