[#579] Issue error when aggregate functions are used in UPDATE (in WHERE or SET clause) or DELETE command (in WHERE clause)
Background
----------
* This commit fixes the following issues
  - https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/579#note_1100865270
  - https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/579#note_1101065077

* The below is pasted from the above two comments.

* This is an issue I noticed while trying out some #770 tests. Using an aggregate function in the SET clause
  of the UPDATE causes a SIG-11 in Octo.

  **Octo output**
  ```sql
  OCTO> create table tmp (id integer);
  CREATE TABLE

  OCTO> update tmp set id=max(id);
  octo: src/optimization_transforms/lp_verify_structure.c:528: lp_verify_structure_helper: Assertion `LP_SELECT_QUERY == options->lp_select_query->type' failed.
  %YDB-F-KILLBYSIGSINFO1, YottaDB process 29318 has been killed by a signal 6 at address 0x00007F1788C80A7C (vaddr 0x000000E400007286)
  ```

* Postgres issues an error that such usage is not allowed.

  **Postgres output**
  ```sql
  names=> update tmp set id=max(id);
  ERROR:  aggregate functions are not allowed in UPDATE
  LINE 1: update tmp set id=max(id);
                            ^
  ```

* Below are a few more examples that have the same issue. One is from the DELETE command. The other is in
  the UPDATE command where aggregate function is used in the WHERE clause (not the SET clause like in the
  original example).

  ```sql
  OCTO> delete from tmp where max(id) = 2;
  octo: src/optimization_transforms/lp_verify_structure.c:528: lp_verify_structure_helper: Assertion 'LP_SELECT_QUERY == options->lp_select_query->type' failed.

  OCTO> update tmp set id = 1 where max(id) = 3;
  octo: src/optimization_transforms/lp_verify_structure.c:528: lp_verify_structure_helper: Assertion 'LP_SELECT_QUERY == options->lp_select_query->type' failed.
  ```

* Below is the output of Postgres to understand the desired behavior in Octo.

  ```sql
  names=> delete from tmp where max(id) = 2;
  ERROR:  aggregate functions are not allowed in WHERE
  LINE 1: delete from tmp where max(id) = 2;
                                ^
  names=> update tmp set id = 1 where max(id) = 3;
  ERROR:  aggregate functions are not allowed in WHERE
  LINE 1: update tmp set id = 1 where max(id) = 3;
                                      ^
  ```

Issue
-----
* Aggregate function usage in the WHERE or SET clause of an UPDATE command or the WHERE clause of a DELETE
  command should issue an error.

Fix
---
* Aggregate function usage in the WHERE clause of an UPDATE or DELETE command now issues the pre-existing
  `ERR_AGGREGATE_FUNCTION_WHERE` error.

* Aggregate function usage in the SET clause of an UPDATE command now issues a new `ERR_AGGREGATE_FUNCTION_UPDATE`
  error.

Implementation details
----------------------
* New macros `AGGREGATE_DEPTH_UPDATE_SET_CLAUSE` and `QualifyQuery_UPDATE_SET_CLAUSE` were introduced
  in `octo.h` and `octo_types.h` (similar to `AGGREGATE_DEPTH_WHERE_CLAUSE` and `QualifyQuery_WHERE`).

* New macros `SET_QUALIFY_STAGE` and `RESET_QUALIFY_STAGE` in `qualify_query.c` help record if we are in
  the WHERE clause of a DELETE or UPDATE or in the SET clause of an UPDATE. This is later used in
  `qualify_statement.c` to issue one of the following 2 errors.
  - ERR_AGGREGATE_FUNCTION_WHERE
  - ERR_AGGREGATE_FUNCTION_UPDATE

* While at this, I noticed 2 pre-existing issues in `qualify_statement.c`.
  - It had code to check if a `parent_table_alias` was non-NULL in various `switch/case` code paths as
    this was possible in case of an UPDATE/DELETE command.

    A cleaner fix for this would be to ensure that is set to non-NULL even for an UPDATE/DELETE and that
    is what I now do using a new `SET_PARENT_TABLE_ALIAS_TO_SELF` macro in `qualify_query.c`.

    This simplified some of the code in `qualify_statement.c` as they can now assume `parent_table_alias`
    is guaranteed to be non-NULL.

  - The `ERR_AGGREGATE_FUNCTION_WHERE` error syntax highlighting was not consistent.

    Take the below examples.

    ```sql
    OCTO> select 1 from names where id = max(1);
    [ERROR]: ERR_AGGREGATE_FUNCTION_WHERE: Aggregate functions are not allowed in WHERE
    LINE 1: select 1 from names where id = max(1);
                                           ^^^
    OCTO> select 1 from names where id = max(id);
    [ERROR]: ERR_AGGREGATE_FUNCTION_WHERE: Aggregate functions are not allowed in WHERE
    LINE 1: select 1 from names where id = max(id);
                                               ^^
    ```

    In the first example above, the `^^^` highlight is below the `max` function name
    which is right but in the second example, the `^^^` highlight is below the `id` column name
    (not the `max` function name).

    This inconsistency is not desirable. It is better for the `ERR_AGGREGATE_FUNCTION_WHERE` error
    to highlight the aggregate function name and not some part of the expression passed inside
    the function as a parameter.

    This is fixed in `qualify_statement.c` by invoking `yyerror(&af->parameter->loc, ...)` all the
    time after issuing a `ERR_AGGREGATE_FUNCTION_WHERE` error whereas previously we used to invoke
    `yyerror(NULL, NULL, &aggr_deepest_column_alias_stmt, ...)` in some cases.

    A consequence of this change was that various existing test reference files now have slightly
    different syntax highlighting output and needed to be fixed.

Test
----
* A new `test_aggregate_functions/TAF05` bats subtest verifies this fix.