[#694] Various issues with generating cross reference plans (_ydboctoX*.m files)
Background
----------
Octo currently employs 2 safeguards when generating physical plans.

1. When Octo generates physical plans (`_ydboctoP*.m` files), it checks its internal database of
   known plan names. If a file with that plan name already exists but Octo has no knowledge of such a
   plan name in its internal database, it regenerates/recreates the plan/file.

2. Octo obtains a lock before creating the physical plan (`_ydboctoP*.m` file). This ensures that
   multiple processes which try to create the same plan at the same time are serialized instead of
   interfering with each other's work and generating a garbled plan.

But turns out neither of these 2 safeguards are currently employed for cross reference plans
(`_ydboctoX*.m` files). This means in rare conditions it is possible for 2 processes to generate the
same cross reference plan at the same time and issue hard-to-debug errors like the following.

1. The below error was seen because an outdated cross reference plan existed as a file in the filesystem
   but Octo had no tracking for it and so a newer build of Octo did not recreate the plan but tried to
   reuse the outdated plan and encountered errors.

   ```sql
   ERROR: YottaDB error: 150373194,populateXref+6^%ydboctoXl1ZF8QChmrFXG5Ip2jah7D,%YDB-E-LABELMISSING, Label referenced but not defined: colvalue2null;
   Error while executing the query
   ```

2. The below is an error that was seen when manually trying to generate the same cross reference plan
   by two concurrently running processes (both of them going through the debugger to get the timing right
   to show the issue) that generate different physical plans (`_ydboctoP*.m` file) but generate the same
   cross reference plan (`_ydboctoX*.m` file). The queries used for this test were `select firstname
   from names where lastname = 'abcd';` and `select lastname from names where lastname = 'abcd';`. And
   in the debugger, a break point was set in `emit_physical_plan.c:151` where the `access()` system call
   is done. Both of them can end up there at the same time which is enough to then get errors like the
   following because both processes will be trying to write to the same file at the same time then on.

   ```sql
   [ERROR] src/run_query.c:345 2021-03-05 15:46:20 : ERR_YOTTADB : YottaDB error: 150374466,octoPlan0+1^%ydboctoPOLcJTapQHMlksD6v67hrEH,%YDB-E-FMLLSTMISSING, The formal list is absent from a label called with an actual list:
   ```

Fixes
-----
* `src/run_query.c` had logic which checked whether the physical plan existed. If so, it checked if Octo
  had knowledge of that plan in its internal global nodes (using `GET_PLAN_METADATA_DB_NODE` macro).
  And it did these checks once outside of an M lock and once inside the M lock before proceeding to generate
  the plan with exclusive access. But all this was being done only for physical plans (`_ydboctoP*.m` files).
  Not for xref plans (`_ydboctoX*.m` files) which were generated in `src/physical/emit_physical_plan.c`.

  This part of the code in `src/run_query.c` is now moved to `src/physical/emit_physical_or_xref_plan.c`, a
  new file that is now invoked from `src/run_query.c` as well as `src/physical/emit_physical_plan.c`. That
  addresses the main issue.

  This change also caused a few `INFO_REUSE_M_PLAN` message to show up in the `octo -vv` (i.e. verbose) output
  for xref plans (just like they used to show up for physical plans).

* But in order for the `GET_PLAN_METADATA_DB_NODE` macro to work for xref plans, we also need to store the
  output key for the xref plan. This was previously done only for physical plans in `src/emit_select_statement.c`.
  So that logic is now moved from there into `src/physical/emit_physical_or_xref_plan.c` so the output
  key is stored in internal Octo gvns for BOTH physical and xref plans.

  This change caused a few reference file fixes as `^%ydboctoocto("plan_metadata",...)` nodes now showed up for
  xref plans too.

* The core logic in `src/physical/emit_physical_plan.c` that previously generated the xref plan is now moved
  into a new file `src/physical/emit_xref_plan.c` to be clear.

* Additionally, `src/physical/emit_physical_plan.c` used to record the full path of the plan srcdir and
  objdir in internal gvns so a later `DISCARD ALL`, `DROP TABLE` etc. know to clean up the plans as appropriate.
  This was done only for physical plans and not xref plans. This is now fixed by moving this logic into a new
  file `src/store_plandirs_gvn.c` that is now invoked from `src/physical/emit_physical_plan.c` (for the physical
  plan case) and from `src/physical/emit_xref_plan.c` (for the xref plan case).

* A new `test_physical_plans/TPP09` bats subtest verifies the main fix by deleting the internal xref plan
  related gvns in Octo, but not deleting the actual xref plan (`_ydboctoX*.m` file) and verifying that rerunning
  the query does regenerate the xref plan.

  On a related note, a new test `test_physical_plans/TPP08` bats subtest tests that an xref plan gets
  regenerated if a physical plan that relies on it gets regenerated. This is not a test of the code fixes
  in this commit in the sense this test passes even in the master branch. But it seemed like a good test to
  have so added it.

Misc fixes
----------
* While reviewing related code, noticed an incorrect/outdated comment in `src/aux/_ydboctoDiscard.m` and fixed it.

* In `src/CMakeLists.txt` reordered `store*.c` file names so they are in sorted order.