[#1041] Allow COERCE_TYPE operations to have PARAMETER_VALUE type as value for pre_coerce_type
Issue
-------
* An assert fails when following query is run in squirrel. It is also reproducible using a `PreparedStatement` test.
  ```sql
  select $1::varchar;
  ```
* Steps to reproduce the failure in squirrel is as shown below
  1. Create user, Start rocto, Open squirrel
  2. Run `select $1::varchar;`
  3. Assert failure is seen in rocto log as shown below
  ```
  [ INFO] YDBOcto/src/run_query.c:191 2024-08-02 13:23:39: INFO_PARSING_DONE: Parsing done for SQL command [select $1::varchar]
  [ INFO] YDBOcto/src/run_query.c:209 2024-08-02 13:23:39: INFO_CURSOR: Generating SQL for cursor 391
  [TRACE] YDBOcto/src/run_query.c:258 2024-08-02 13:23:39: INFO_ENTERING_FUNCTION: Entering hash_canonical_query
  rocto: YDBOcto/src/hash_canonical_query.c:450: hash_canonical_query: Assertion `IS_LITERAL_PARAMETER(value->u.coerce_type.pre_coerced_type) || IS_NUL_VALUE(value->u.coerce_type.pre_coerced_type) || ((IS_DATE_TIME_DATA_TYPE(coerced_type->data_type)) && (PARAMETER_VALUE == value->u.coerce_type.pre_coerced_type))' failed.
  ```
* For the same query non-debug build generates the following error
  ```
  [ERROR] YDBOcto/src/rocto/handle_bind.c:245 2024-08-06 10:57:30: ERR_ROCTO_INVALID_NUMBER_BIND_PARAMETERS: handle_bind: invalid number of parameters: expected 1 got 0)
  ```
* Need to check why the assert fails and fix it

Analysis
---------
* The assert failure is only seen with COERCE operations
* For extended query protocol following steps happen (copied from postgres.tutor)
  ```
   163         Extended query protocol
   164                 parse step         -> handle_parse.c     (creates prepared statement from text query string)
   165                 bind  step         -> handle_bind.c      (creates portal             from prepared statement)
   166                 execute step       -> handle_execute.c   (runs portal's query)
  ```
* During the parse step, the assert statements for `COERCE_TYPE` are trying to ensure the value being
  coerced is of a known type i.e. like `INTEGER_LITERAL`, `STRING_LITERAL` and not `PARAMETER_VALUE` or `UNKNOWN_SQL_TYPE`.
* For the query described above the type of the value being coerced is treated as `PARAMETER_VALUE`, this results in the assert to fail.
* Type can be a `PARAMETER_VALUE` in the following cases
  1. When the prepared statement has a parameter value but its type is unknown. This happens if functions like
     `preparedStatement.setObject(1 ,java.sql.Date.valueOf("2016-06-30"));` are used.
  2. When `$1` is used to form the prepared statement query as shown below.
     ```
     preparedStatement = conn.prepareStatement("select $1::varchar");
     ```
     * Note parameters are expected to be specified in `preparedStatement` using `?`, when this is done if a parameter is not set following error is issued
       before Rocto is even passed the query.
       ```
       SQL State: 22023
       No value specified for parameter 1.
       ```
* In both the above cases there is no way for parser to know the actual type
* It is better for the asserts to handle this case and let bind step take care of checking whether the parameter is sent or not
* If parameter is not passed then the query will fail in `bind step` with the following error
  ```
  [ERROR] YDBOcto/src/rocto/handle_bind.c:245 2024-08-06 10:57:30: ERR_ROCTO_INVALID_NUMBER_BIND_PARAMETERS: handle_bind: invalid number of parameters: expected 1 got 0)
  ```
  Similar error is seen when Postgres is used as the server
  ```
  -- Following is the error seen from squirrel with Postgres as the server
  Error: ERROR: bind message supplies 0 parameters, but prepared statement "" requires 1
  SQLState:  08P01
  ErrorCode: 0
  ```

Fix
----
* Update assert's in `COERCE_TYPE` case statement of hash_canonical_query.c and tmpl_print_expressions.ctemplate to allow `pre_coerce_type` to be `PARAMETER_VALUE`.
* Previously, `PARAMETER_VALUE` was allowed only when the value was coerced to date/time type. To allow `PARAMETER_VALUE` for all types of coercions following
  change removed the condition which added the date/time limitation in hash_canonical_query().
  ```
  @@ -449,8 +449,7 @@ void hash_canonical_query(hash128_state_t *state, SqlStatement *stmt, int *statu
   			 */
   			assert(IS_LITERAL_PARAMETER(value->u.coerce_type.pre_coerced_type)
   			       || IS_NUL_VALUE(value->u.coerce_type.pre_coerced_type)
  -			       || ((IS_DATE_TIME_DATA_TYPE(coerced_type->data_type))
  -				   && (PARAMETER_VALUE == value->u.coerce_type.pre_coerced_type)));
  +			       || (PARAMETER_VALUE == value->u.coerce_type.pre_coerced_type));
  ```

Test
----
* TJC022 is added to test the case which resulted in assert failure previous to this change
* TJC023 is added to test cases which pass values whose type mismatch with the coerce type