[#1061] Fix boolean value handling of INSERT queries to process 't' and 'f' as 1 and 0
Issue (copied from description of #1061)
------
@nars1 came across this issue when reviewing !1581. Boolean literals like 't' and 'f' are considered as `VARCHAR`s in the following insert query.
```
Queries:
create table test (id int, foo boolean);
insert into test values(1, 't');
insert into test values(2, 'f');
insert into test values(3, 'yes');
.

Octo result:
OCTO> create table test (id int, foo boolean);
CREATE TABLE
OCTO> insert into test values(1, 't');
[ERROR]: ERR_INSERT_TYPE_MISMATCH: Column "foo" is of type BOOLEAN but expression is of type VARCHAR
OCTO> insert into test values(2, 'f');
[ERROR]: ERR_INSERT_TYPE_MISMATCH: Column "foo" is of type BOOLEAN but expression is of type VARCHAR
OCTO> insert into test values(3, 'yes');
[ERROR]: ERR_INSERT_TYPE_MISMATCH: Column "foo" is of type BOOLEAN but expression is of type VARCHAR
.

Postgres:
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
.
names=> select * from test;
 id | foo
----+-----
  1 | t
  2 | f
  3 | t
  .
```
Notice when a `SELECT` is used instead of `values` the `INSERT` succeeds. But the data seen in the table is `VARCHAR` data.
```
Queries:
insert into test select 1, 't';
insert into test select 2, 'yes';
insert into test select 3, 'no';
select * from test;

Octo's output:
OCTO> insert into test select 1, 't';
INSERT 0 1
OCTO> insert into test select 2, 'yes';
INSERT 0 1
OCTO> insert into test select 3, 'no';
INSERT 0 1
OCTO> select * from test;
id|foo
1|t
2|yes
3|no
(3 rows)

Postgres Output:
INSERT 0 1
INSERT 0 1
INSERT 0 1
 id | foo
----+-----
  1 | t
  2 | t
  3 | f
(3 rows)
```
Octo is treating the value passed to `foo` as `VARCHAR`. This is incorrect and needs to be fixed.

Analysis
---------
Consider the insert statement with `values`, the `ERR_INSERT_TYPE_MISMATCH` is thrown by src/check_column_lists_for_type_match.c
when src/populate_data_type.c invokes it to process insert_STATEMENT.

In src/check_column_lists_for_type_match.c, the column type was found to be `BOOLEAN_VALUE` (`right_type`) and the literal to be
inserted was found to be `STRING_LITERAL` (`left_type`). Line 166 below sets `is_type_mismatch` to TRUE and the immediate if-else
doesn't do anything else. This leads to ERR_INSERT_TYPE_MISMATCH being thrown at the end of this file.

**src/check_column_lists_for_type_match.c**
```
165                         case STRING_LITERAL:
166                                 is_type_mismatch = !IS_STRING_TYPE(right_type);
167                                 if (BOOLEAN_OR_STRING_LITERAL == right_type) {
168                                         assert(is_set_operation);
169                                         FIX_TYPE_TO_STRING_LITERAL(cur_cla[1]->type);
170                                         fixed_type = TRUE;
171                                 } else if (IS_DATE_TIME_TYPE(right_type)) {
172                                         is_type_mismatch = FALSE;
173                                         if (is_set_operation) {
174                                                 // Add a cast operation at cur_cla[0]->column_list->v.column_list->value
175                                                 // ensure_same_type.c has similar checks any change here should also reflect there
176                                                 cur_cla[0]->type = right_type;
177                                                 SqlColumnList *column_list;
178                                                 UNPACK_SQL_STATEMENT(column_list, cur_cla[0]->column_list, column_list);
179                                                 ADD_DATE_TIME_TIMESTAMP_CAST_STMT(column_list->value, right_type, left_type);
180                                         } /* else this is an insert operation allow it here to prevent the use of date/time prefix
181                                            * to literals. The value itself is validated in M code later on.
182                                            */
183                                 }
184                                 break;
```

The literal is changed to be `STRING_LITERAL` from `BOOLEAN_OR_STRING_LITERAL` in populate_data_type() because there is only
one row and we cannot determine it to be a boolean without another row having a `BOOLEAN_VALUE` for the same column. Following
code is responsible for type change. Line 1165 is where the type of literal is changed to `STRING_LITERAL`.

**src/populate_data_type.c**
```
1146                                 if (saw_boolean_or_string_literal) {
1147                                         /* Found at least one column value whose type is BOOLEAN_OR_STRING_LITERAL.
1148                                          * Rescan all the table rows/columns and fix those column values which are of type
1149                                          * BOOLEAN_OR_STRING_LITERAL to be type BOOLEAN_VALUE or STRING_LITERAL as appropriate.
1150                                          */
1151                                         row_value = start_row_value;
1152                                         do {
1153                                                 SqlColumnList *start_column_list, *cur_column_list;
1154
1155                                                 UNPACK_SQL_STATEMENT(start_column_list, row_value->value_list, column_list);
1156                                                 cur_column_list = start_column_list;
1157                                                 colno = 0;
1158                                                 do {
1159                                                         if (saw_boolean_or_string_literal_array[colno]) {
1160                                                                 SqlValueType fix_type2, type2;
1161
1162                                                                 assert((BOOLEAN_OR_STRING_LITERAL == type_array[colno])
1163                                                                        || (STRING_LITERAL == type_array[colno])
1164                                                                        || (BOOLEAN_VALUE == type_array[colno]));
1165                                                                 fix_type2 = (BOOLEAN_OR_STRING_LITERAL == type_array[colno])
1166                                                                                 ? STRING_LITERAL
1167                                                                                 : type_array[colno];
1168                                                                 result |= populate_data_type(cur_column_list->value, &type2, v,
1169                                                                                              parse_context, &fix_type2);
1170                                                                 assert(!result); /* type fixing call of "populate_data_type" should
1171                                                                                     never fail as it is 2nd call */
1172                                                                 UNUSED(result);  /* to avoid [clang-analyzer-deadcode.DeadStores]
1173                                                                                     warning */
1174                                                                 assert((fix_type2 == type2) || IS_NUL_VALUE(type2));
1175                                                         }
1176                                                         colno++;
1177                                                         cur_column_list = cur_column_list->next;
1178                                                 } while ((cur_column_list != start_column_list));
1179                                                 row_value = row_value->next;
1180                                         } while (row_value != start_row_value);

```

For this query, we need to convert the column to be boolean type if the STRING_LITERAL values can be converted successfully to
boolean values. A mismatch error should be thrown if its not possible to determine the compatibility and ERR_INVALID_BOOLEAN_SYNTAX
error should be thrown if the value cannot be converted. From experimentation it was confirmed that Postgres does the same. Only
queries like `insert tbl values(1,'t'),(2,'yes');` are transformed such that `'t'` and `'yes'` are treated as `TRUE`. Queries like
`insert tbl values((select 1), (select 't')),((select 2), (select 'yes'));` throw MISMATCH error.

The second usecase which is of concern is `insert into tbl select 1, 't';`. In master branch this query doesn't throw an error.
This is because of the following case block. The type of the literal will be `BOOLEAN_OR_STRING_LITERAL` when
this part of the code is reached. Here based on the src table column type the literal value type is fixed. The type it is fixed to
is `BOOLEAN_VALUE`. This leads to tmpl_insert_into.ctemplate inserting the literal value without checking if the value is valid or
converting it into a standard boolean format.

**src/check_column_lists_for_type_match.c**
```
│      185                          case BOOLEAN_OR_STRING_LITERAL:					   │
│      186                                  switch (right_type) {   					   │
│      187                                  case BOOLEAN_VALUE:    					   │
│      188                                  case STRING_LITERAL:   					   │
│  >   189                                          is_type_mismatch = FALSE;  				   │
│      190                                          if (BOOLEAN_VALUE == right_type) {    		   │
│      191                                                  FIX_TYPE_TO_BOOLEAN_VALUE(cur_cla[0]->type);   │
│      192                                          } else {                                               │
│      193                                                  FIX_TYPE_TO_STRING_LITERAL(cur_cla[0]->type);  │
│      194                                          }                                                      │
│      195                                          fixed_type = TRUE;                                     │
│      196                                          break;
```

Because of this, if the literal value is `'abcd'` then it is stored as the boolean value which is incorrect. Also, even if `'t'`
and `'f'` are used which are valid boolean literals we want them to be converted to `1` and `0` before inserting it to the result
table. This doesn't happen which is incorrect.

Both the cases can be handled by going down the parse tree and modifying the literal
value to the standard boolean value of 1 or 0. If its not possible to determine the value easily then mismatch error needs to be
thrown and if the literal value is found to be invalid then appropriate error needs to be thrown.

Change
--------
* src/check_column_lists_for_type_match.c is updated to handle the case where the value being inserted is determined to be a `STRING_LITERAL`
  and the table column to which it is inserted to is of type `BOOLEAN_VALUE`. The changes done is explained below
  * If the src table (the table which has the values to be inserted) is a set_operation_STATEMENT then MISMATCH error is issued
  * If its a table_value_STATEMENT then we go down the parse tree to check if columns of the VALUES clause are of type value_STATEMENT.
    Only in this case we see if its possible to convert the STRING_LITERAL to BOOLEAN_VALUE. If it is then the value is transformed (i.e.
    from 't' or 'f' and similar boolean values to 1 and 0). If the value cannot be transformed ERR_INVALID_BOOLEAN_SYNTAX is thrown.
    If columns are not of type value_STATEMENT then ERR_TYPE_MISMATCH error is thrown.
  * If the src table is select_STATEMENT then we throw ERR_INVALID_BOOLEAN_SYNTAX error as we will have a STRING_LITERAL type for the
    column to be inserted only if it couldn't be converted to a BOOLEAN_VALUE by populate_data_type.c. So no additional processing
    needed.
  * This handled all the cases where the value being inserted was determined to be a STRING_LITERAL and column to which it was inserted
     is of type BOOLEAN_VALUE. The behavior exhibited by Octo now is identical to Postgres for these cases.
* Also, src/check_column_lists_for_type_match.c is updated to handle the case where the value being inserted is determined to be a
  `BOOLEAN_OR_STRING_LITERAL` and the table column to which it is inserted to is of type `BOOLEAN_VALUE`. The changes done is
  explained below
  * If the src table (the table which has the values to be inserted) is a set_operation_STATEMENT then MISMATCH error is thrown
  * We do not expect to have a src table of type table_value_STATEMENT here so an `assert(FALSE)` is placed in this code path
  * When the src table is a select_STATEMENT we are sure that the underlying column is a value_STATEMENT so we go down the
    parse tree to fix the literal to a boolean value. If the literal is not a valid boolean value then we throw
    ERR_INVALID_BOOLEAN_SYNTAX error.
* An insert with select previously added string literals without any validation to result table. With this change
  the literal being inserted is validated and then converted to 0 or 1 before adding it to the result table.
* Above changes fixed both the issues noticed with insert queries.
* For example, following is the output from Postgres for such queries
  ```
  names=> insert into tbl select 1, 'asdf';
  ERROR:  invalid input syntax for type boolean: "asdf"
  LINE 1: insert into tbl select 1, 'asdf';
                                      ^
  names=> insert into tbl values(1, 'asdf');
  ERROR:  invalid input syntax for type boolean: "asdf"
  LINE 1: insert into tbl values(1, 'asdf');

  names=> insert into tbl values(1, 't');
  INSERT 0 1
  names=> insert into tbl select 1, 'yes';
  INSERT 0 1
  names=> select * from tbl;
   id | foo
  ----+-----
    1 | t
    1 | t
  (2 rows)
  ```
  Output of Octo after this change is similar to Postgres
  ```
  OCTO> insert into tbl values(1, 'asdf');
  [ERROR]: ERR_INVALID_BOOLEAN_SYNTAX: Invalid input syntax for type boolean: 'asdf' is not a valid boolean value
  OCTO> insert into tbl select 1, 'asdf';
  [ERROR]: ERR_INVALID_BOOLEAN_SYNTAX: Invalid input syntax for type boolean: 'asdf' is not a valid boolean value

  OCTO> insert into tbl values(1, 't');
  INSERT 0 1
  OCTO> insert into tbl select 1, 't';
  INSERT 0 1
  OCTO> select * from tbl;
  id|foo
  1|t
  1|t
  (2 rows)
  ```
* src/check_column_lists_for_type_match.c is invoked by src/populate_data_type.c to process set_operation_STATEMENT
  and insert_STATEMENT. The changes done in this commit only affects insert_STATEMENT execution.

Test
-----
* TBT15 is added to validate the changes done in this commit
* Queries in TBT13 which is now fixed because of this change is moved to TBT15
* More queries are added to TBT13 to validate few error case

Misc
------
* Changes done to src/m_templates/tmpl_physical_plan.ctemplate removes an additional line being inserted
  for insert query plans. Refer to the comment in
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1593#note_2162095188 for more details on this change.
* Changes done to `ForceBoolean` and `String2Boolean` routines in src/aux/_ydboctoplanhelpers.m helps avoid
  duplication and performance concerns expressed in this comment ->
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1593#note_2163696810.