[#1079] Fix LSEXPECTED/FMLLSTMISSING errors from M plans of some long SQL queries
Background
----------
This was found as an occassional failure (about 1/10 times) in TSCP29.
The test error showed this:
```
SQL State: XX000
ERROR: YottaDB error: 150374466,run+8^%ydboctoselect,%YDB-E-FMLLSTMISSING, The formal list is absent from a label called with an actual list:
```

Further investigation on that specific SQL file (`test8.sql`) showed
that the actual error is similiar to the following:
```
%YDB-W-LSINSERTED, Line 3, source module /extra3/builds/octo/bats-test.2qa38D/_ydboctoPdgEKjwOeoxEMGHmnuSmEEK.m exceeds maximum source line length; line seperator inserted, terminating scope of any prior IF, ELSE, or FOR
        a'
         ^-----
	At column 2, line 3, source module /extra3/builds/octo/bats-test.2qa38D/_ydboctoPdgEKjwOeoxEMGHmnuSmEEK.m
%YDB-E-LSEXPECTED, A line separator is expected here
[ERROR]: ERR_YOTTADB: YottaDB error: 150374466,run+8^%ydboctoselect,%YDB-E-FMLLSTMISSING, The formal list is absent from a label called with an actual list:
```

The core of the issue is that the comment containing the SQL query that
the plan corresponds to is too long, but only if it is 32765-32768
characters long. Shorter and Longer queries are fine.

As to why this error just started happening now and not earlier, we don't
have definive explanations. It's likely due to glibc changes or bash
changes (perhaps it randomizes better now). If we remove randomization,
the failure is reproducible all the time (see
https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1652#note_2667223722).

- The reason for why the failure only happens very rarely is
  because test4.sql, test5.sql, test6.sql, test7.sql, test8.sql
  and test9.sql all end up generating the same M plan normally (in M or
  UTF-8 mode). But if they go through the JDBC driver and extended
  protocol is randomly chosen by the test framework, then a LIMIT keyword
  gets added to the query (see #1014 for more details) and
  because of this, the generated M plan is different than if it does not
  go through the JDBC driver OR through the JDBC driver with extended
  protocol disabled. And TSCP29 subtest invokes
  run_query_in_octo_and_postgres_and_crosscheck_multiple_queries for each
  of test4.sql to test9.sql. And each invocation can randomly choose JDBC
  protocol (with useextended) or not. And because of this different plans
  get generated. And if it so happens that the JDBC + useextended option
  gets randomly chosen for test8.sql or test9.sql (the ones with long
  enough lines to expose #1079) AND it was not chosen for the prior
  test4.sql to test7.sql invocations, that is only when the test fails.
  Hence the rarity of the failure. See discussion at
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1652#note_2664698548,
  and
  https://gitlab.com/YottaDB/DBMS/YDBOcto/-/merge_requests/1652#note_2667223722.
- The reason the bug is shown with test8.sql or test9.sql is the
  query is generated using the line `yottadb -r test8^TSCP29 >
  test8.sql`, and YottaDB by default wraps lines longer than 32k (test8
  line is about 90k in size), the query ended up being 3 lines long
  split. The reason it's about 90k in size is that the test creates
  strings of 32k characters each, but the characters in test8 and test9
  are Chinese Kanji, each of which occupy 3 bytes, thus resulting in a
  long string that is split by YottaDB.

Fix
---
There were multiple issues:

- There were two conflicting macros being used for line length
	- M_LINE_MAX 32768 (incorrect), currently in use
	- MAX_M_LINE_LEN 32766 (correct), but not used
- The counting for line length forgot to count the "  ;\n" that is part
  of the line.
- The query supplied is supposed to be supplied in a single line, and is
  not supposed to contain line breaks. However, due to the fact that the
  query is generated using the line `yottadb -r test8^TSCP29 >
  test8.sql`, and YottaDB by default wraps lines longer than 32k (test8
  line is about 90k in size), the query ended up being 3 lines long
  split.

So the fixes done are:
- M_LINE_MAX was dropped, and MAX_M_LINE_LEN used instead.
- Line length counting was fixed.
- In addition, the comment and code said an elipsis was going to be added
  yet it wasn't there. Now added.
- The M code that generates the SQL queries has been fixed so it won't
  wrap the queries anymore.

The fix has a pre-existing limitation: It does not truncate UTF-8 at
character boundaries. I decided it's not worth trying to fix this now
as this is rare. It can be fixed in the future. Tracked at #1089.

Test
----
New `TPP11` test that creates 4 queries from 32765 to 32768 bytes long
and ensures that they run successfully. The test takes 15 seconds to
run... most of the time is spent in octo parsing the long strings and
running the query.