[#868] Correct ORDER BY ambiguity resolution when select list has an input column with the same name as alias of other column in the select list
**Issue**

When an ORDER BY column name matches multiple column names in SELECT list irrespective of whether user specified it or not, an ambiguity error is expected to be issued. At present, Octo only considers matching ORDER BY column names with user specified aliases in SELECT list, because of this the example query shown below doesn't result in the expected error.
```sql
OCTO> select 'Zero' != 'Zero' as firstname,firstname from names order by firstname;
FIRSTNAME|FIRSTNAME
0|Zero
0|Acid
0|Cereal
0|Lord
0|Joey
0|Zero
(6 rows)
```
In the above query, `firstname` in ORDER BY matches both `'Zero' != 'Zero' as firstname` and second column `firstname` in SELECT list. But since Octo only considers user specified alias to determine ambiguity there is no error issued. This has to be corrected to issue an error similar to the following example from Postgres.

Expected:
```sql
names=> select 'Zero' != 'Zero' as firstname,firstname from names order by firstname;
ERROR:  ORDER BY "firstname" is ambiguous
LINE 1: ...'Zero' as firstname,firstname from names order by firstname;
                                                             ^
```
Note:
* Only a column reference in select list should be considered for matching a column name in ORDER BY even if it doesn't have an user specified alias name. In such a case the alias name of the column reference in select list will be its column name itself. If an expression is present in select list without a user specified alias name, such columns should not be considered for matching a column name in ORDER BY. This is because when user has not specified an alias for the expression, its alias in Octo will be the first column reference name seen in it and matching this will be incorrect. Postgres doesn't do such matching as well.
* Both of the following ORDER BY related rules seen in Postgres documentation where already implemented in Octo. This change implements a third rule which is described before this note section. This third rule doesn't have clear documentation in Postgres but was identified by trying out queries.
  * From Postgres [documentation](https://www.postgresql.org/docs/14/sql-select.html#SQL-ORDERBY) _If an ORDER BY expression is a simple name that matches both an output column name and an input column name, ORDER BY will interpret it as the output column name._
  * From Postgres [documentation](https://www.postgresql.org/docs/current/queries-order.html) _an output column name has to stand alone, that is, it cannot be used in an expression_

**Code change**
* Solving the ambiguity resolution logic itself was simple. We used to consider only user specified alias names in select list to match a given column name. Now, this logic in qualify_column_name.c is updated to consider non-user specified column reference aliases in select list along with user specified aliases for column name matching.
* As seen in the **Test** section below, this change results in plan name change as a result FMT_PLAN_DEFINITION is updated from 16 to 17.

**Test**
* TOB18 is added to verify this change
* tests/outref/TEO03.ref and tests/outref/TW25.ref are updated as plan name and as a result sort order changed. This plan name change is because, SELECT list column was selected instead of FROM clause table column during ORDER BY column name matching. This change in association is because of the change mentioned in **Code change** section. As SELECT list column structure includes alias information (this alias information is absent in FROM clause table column structure), hash_canonical_query() generated a different name than what was originally present (i.e. when FROM clause table column was matched instead of SELECT list column).
* tests/outref/TSQ009.ref is updated as the logical plan has an additional ALIAS entry for ORDER BY column. The new addition is because of the same reason mentioned in previous point, ORDER BY column is matched to SELECT list column instead of FROM clause table column and as a result the ALIAS information which is present in SELECT list column is present now in ORDER BY column as well.
* TGB21_errors.ref is updated because after this change error message excluded location pointers on the ORDER BY node as this information is lost during ORDER BY alias replacement. This replacement was not done prior to this change because ORDER BY column name matching skipped SELECT list column references without user specified aliases but with this change such column references are also considered for column name matching. As a result, the ORDER BY column is matched with SELECT list column resulting in ORDER BY column alias replacement. This replacement causes the location information loss and thus the absence of location related message in error message.

**Doc**
* ORDER BY section in doc/grammar.rst is updated to describe ambiguity resolution and also to mention expressions are allowed in ORDER BY.

**Misc**
* GROUP BY section in doc/grammar.rst is updated to describe ambiguity resolution and also to mention that integers are treated as select list columns.
* Few test queries which generate ambiguity error is added to TGB30_errors.sql

**Fallout**
* Usually, an error has two messages, one to denote the ERROR which has occurred and the other to denote the place of occurrence. In case of an alias usage in ORDER BY or a column number usage in ORDER BY qualify_statement() would replace the original column list with the select list column's column list which was referenced by the alias/column number. The result of this logic is that the location information of the replaced column is that of the select list. Because of this the error message which points to where the error has happened will point to select list column itself. This is misleading in few cases. Example query below demonstrates the issue. The first error message is for the select list column where as the second is for the order by column `firstname` but since we do a replace the location information seen will be of the select list and thus ending up with the following output.
```sql
OCTO> select id,firstname as firstname from names group by 1 order by firstname;
[ERROR]: ERR_GROUP_BY_OR_AGGREGATE_FUNCTION: Column FIRSTNAME must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select id,firstname as firstname from names group by 1 order by...
                  ^^^^^^^^^
[ERROR]: ERR_GROUP_BY_OR_AGGREGATE_FUNCTION: Column FIRSTNAME must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select id,firstname as firstname from names group by 1 order by...
                  ^^^^^^^^^
```
* Even though this problem existed before this change its occurrence with this change has increased because more usecases are possible which can generate this type of error.

**Future Todo**
* Fix the misleading error info