[#609] Fix various issues with TRUNCATE
Background
----------
Below are 2 issues pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/609#note_1237682457.

1) TRUNCATE of a non-existent table does not issue any error. We expect an error from Octo just like
   is seen in Postgres below.

   **Octo output**
   ```sql
   OCTO> truncate foo;
   OCTO>
   ```

   **Postgres output**
   ```sql
   names=> truncate foo;
   ERROR:  relation "foo" does not exist
   ```

2) TRUNCATE of an existing table does not issue any information message indicating the truncate succeeded.
   We expect a `TRUNCATE TABLE` message (in both `octo` and `rocto`) just like is seen below in Postgres.

   **Octo output**
   ```sql
   OCTO> truncate names;
   OCTO>
   ```

   **Postgres output**
   ```sql
   names=> truncate names;
   TRUNCATE TABLE
     ```

Below is another issue pasted from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/609#note_1237730670

3) This is another issue I noticed while testing `TRUNCATE`. If I specify `2+3` as the table name, I get
   a SIG-11 in Octo. If I specify `2` as the table name, I get a `ERR_UNKNOWN_TABLE` error. I expected a
   `syntax error` in both cases. Same with `false` as the table name.

   **Octo output**
   ```sql
   OCTO> truncate 2+3;
   %YDB-F-KILLBYSIGSINFO1, YottaDB process 59515 has been killed by a signal 11 at address 0x00007F08E734097D (vaddr 0x0000000000000009)
   %YDB-F-SIGMAPERR, Signal was caused by an address not mapped to an object

   OCTO> truncate 2;
   [ERROR]: ERR_UNKNOWN_TABLE: Unknown table: 2

   OCTO> truncate false;
   [ERROR]: ERR_UNKNOWN_TABLE: Unknown table: 0
   ```

   Below is Postgres output which shows a `syntax error`.

   **Postgres output**
   ```sql
   names=> truncate 2+3;
   ERROR:  syntax error at or near "2"
   LINE 1: truncate 2+3;
                    ^
   ```

   A few other queries at https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/609#note_1237733914 also
   suffered from the same issue as above.

Issue/Fix/Test
--------------
1) When TRUNCATE is attempted on a non-existent table, we issue a `INFO_TABLE_DOES_NOT_EXIST` informational
   message in `src/run_query.c`. But we do not treat it as an error. This means we continue processing
   the truncate for other tables in the input list.

   The fix is to issue a `ERR_UNKNOWN_TABLE` error instead. And treat this as an error situation and
   return with a non-zero exit status from `run_query()` in this case.

   While at this, noticed that the `ERR_TABLE_READONLY` error scenario also did not treat this as an error
   and continued TRUNCATE processing for the remainder of the list of tables. This is also fixed to
   return with a non-zero exit status from `run_query()` right away.

   The following reference files were modified due to the new `ERR_UNKNOWN_TABLE` error.
   - tests/outref/TT01.ref
   - tests/outref/TT03.ref

   `tests/test_truncate.bats.in` was modified to remove the `grep` commands that previously searched for
   the `INFO_TABLE_DOES_NOT_EXIST` message now that this message is no longer printed.

   Since we now stop processing in `run_query()` when an error is noticed, `TRUNCATE` only truncates
   a partial list of tables in case of an error. And therefore, tables following the error point will
   continue to have no rows removed. This is a test in `tests/fixtures/TT02.sql` and so the expected
   output is changed in a comment in that file. This also meant a corresponding reference file in
   `tests/outref/TT02.ref` where the `customers` table now has all rows intact whereas previously it
   used to have no rows.

   Note that even now, TRUNCATE on a list of tables is not an atomic operation and this is not desirable.
   This is tracked at https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/609#note_1237808072 and will be
   fixed in a later commit.

2) When TRUNCATE is attempted on a valid table, we do not issue a `TRUNCATE TABLE` message. This is fixed
   by adding a `PRINT_COMMAND_TAG(TRUNCATE_TABLE_COMMAND_TAG)` call in `src/run_query.c`. This took care
   of the `octo` case. For the `rocto` case, this is taken care of in `src/make_command_complete.c` by
   handling the `truncate_table_STATEMENT` case to print the `TRUNCATE_TABLE_COMMAND_TAG` tag.

   The macro `TRUNCATE_TABLE_COMMAND_TAG` is added to `src/octo.h`.

   The following reference files were modified to include the `TRUNCATE TABLE` tag that now gets printed.
   - tests/outref/TT01.ref
   - tests/outref/TT03.ref

   `tests/test_truncate.bats.in` was enhanced to do a `start_rocto` in the `TT01` subtest to verify that
   rocto also issues the `TRUNCATE TABLE` tag.

3) When a table name of `2+3` is specified, TRUNCATE results in a SIG-11 because the grammar for TRUNCATE
   in `src/parser/truncate.y` lists a `value_expression` in the place where a table name is specified.
   This is incorrect. This is fixed by using a `column_name` instead. But then I realized there is already
   a grammar rule to handle a list of column names `column_name_list` and so used that directly in the
   `TRUNCATE` command. This meant removing the `truncate_list`, `truncate_sublist` and `truncate_sublist_tail`
   rules as they were no longer needed.

   A new `test_truncate/TT04` bats subtest verifies this fix.